#! /usr/bin/env perl
# Copyright 2026 The OpenSSL Project Authors. All Rights Reserved.
#
# Licensed under the Apache License 2.0 (the "License").  You may not use
# this file except in compliance with the License.  You can obtain a copy
# in the file LICENSE in the source distribution or at
# https://www.openssl.org/source/license.html

# Build-time generator for crypto/ec/ec_curves.inc.
# Reads crypto/ec/ec_curves.conf (config-target style data file) and
# configdata.pm (for disabled() / %disabled), emits a C include file with
# the curve structs, the static OSSL_FN constants and BIGNUM views, and
# the curve_list[] tables for the enabled curves.

use strict;
use warnings;
use FindBin;
use lib '.';                    # for configdata.pm
use configdata;

# Helper for the enabled coderefs in ec_curves.conf
sub disabled {
    my ($feature) = @_;
    return exists $disabled{$feature} && $disabled{$feature};
}

# Load the curve data; the file's last expression is a list of
# name => record pairs in curve_list order
my @pairs = do "$FindBin::Bin/ec_curves.conf";
die "Cannot load ec_curves.conf: $@" if $@;
die "Cannot load ec_curves.conf: $!" unless @pairs;

my (@order, %curves);
while (@pairs) {
    my ($name, $record) = splice @pairs, 0, 2;
    push @order, $name;
    $curves{$name} = $record;
}

# ------------------------------------------------------------------
# Helpers
# ------------------------------------------------------------------

# Sanitize a name to a C identifier (same as objects.pl)
sub sanitize {
    my ($name) = @_;
    $name =~ s/-/_/g;
    $name =~ s/\./_/g;
    return $name;
}

# Resolve a record through an alias; returns (canonical_name, record)
sub resolve {
    my ($name) = @_;
    my $c = $curves{$name};
    if (exists $c->{alias_of}) {
        return ($c->{alias_of}, $curves{$c->{alias_of}});
    }
    return ($name, $c);
}

sub is_enabled {
    my ($name) = @_;
    my ($cname, $c) = resolve($name);
    if (exists $c->{enabled} && ref $c->{enabled} eq 'CODE') {
        return $c->{enabled}->();
    }
    return 1;
}

# Convert big-endian hex string to little-endian limb list
sub hex_to_limbs {
    my ($hex) = @_;
    # Left-pad to whole 4-byte words; within each word the bytes are
    # big-endian.
    $hex = '0' x ((8 - length($hex) % 8) % 8) . $hex;
    # Split into 4-byte words, then reverse to little-endian limb order.
    my @words = reverse unpack '(H8)*', pack 'H*', $hex;
    # Emit OSSL_FN_ULONG64_C pairs of words; a trailing odd word becomes a
    # single OSSL_FN_ULONG_C.  This matches OSSL_FN_LIMBS_N() on both 32-
    # and 64-bit platforms.
    my @limbs;
    while (@words) {
        my $lo = shift @words;
        if (@words) {
            my $hi = shift @words;
            push @limbs, "OSSL_FN_ULONG64_C(0x$hi, 0x$lo)";
        } else {
            push @limbs, "OSSL_FN_ULONG_C(0x$lo)";
        }
    }
    return @limbs;
}

# Significant bits of a value given as a hex string; the BIGNUM top field
# (in BN_ULONG units) follows from OSSL_FN_LIMBS_N of this count
sub sig_bits {
    my ($hex) = @_;
    $hex =~ s/^0+//;   # strip leading zeros
    return 0 if $hex eq '';
    my $top = hex(substr $hex, 0, 1);
    my $bits_in_top = $top >= 8 ? 4 : $top >= 4 ? 3 : $top >= 2 ? 2 : 1;
    return 4 * (length($hex) - 1) + $bits_in_top;
}

# Escape a string for embedding in a C string literal
sub c_string {
    my ($s) = @_;
    $s =~ s/\\/\\\\/g;
    $s =~ s/"/\\"/g;
    $s =~ s/\n/\\n/g;
    $s =~ s/\t/\\t/g;
    return $s;
}

# Emit a byte array initializer, 12 bytes per line
sub emit_bytes {
    my ($hex) = @_;
    die "odd number of hex digits\n" if length($hex) % 2;
    my @bytes = unpack '(H2)*', pack 'H*', $hex;
    my @lines;
    while (@bytes) {
        my @chunk = splice @bytes, 0, 12;
        push @lines, '        ' . join(', ', map { "0x$_" } @chunk);
    }
    return join(",\n", @lines);
}

# ------------------------------------------------------------------
# Generate
# ------------------------------------------------------------------

my @enabled = grep { is_enabled($_) } @order;
my @canonical = grep { !exists $curves{$_}{alias_of} } @enabled;

my $output = <<'HEADER';
/*
 * Copyright 2026 The OpenSSL Project Authors. All Rights Reserved.
 *
 * Licensed under the Apache License 2.0 (the "License").  You may not use
 * this file except in compliance with the License.  You can obtain a copy
 * in the file LICENSE in the source distribution or at
 * https://www.openssl.org/source/license.html
 */

/* EC named-curve data, generated by crypto/ec/ec_statics.pl */
/* This file is meant to be included from crypto/ec/ec_curve.c */

#include <openssl/bn.h>
#include <openssl/obj_mac.h>
#include "internal/nelem.h"
#include "crypto/bn/bn_local.h"
#include "crypto/fn_intern.h"

/*
 * The OSSL_FN storage for these constants keeps the full
 * OSSL_FN_LIMBS_N(param_len * 8) limbs for constant-time uniformity, while
 * the BIGNUM view needs the correct top field, expressed as the number of
 * significant limbs (zero top limbs excluded; zero itself has 0 significant
 * bits).  That count is recorded per constant in a companion macro, used
 * by make_ec_bn() below.
 */

typedef struct ec_static_bignum_st {
    const BIGNUM *p, *a, *b, *x, *y, *order, *cof;
} EC_STATIC_BIGNUM;

#define make_ec_bn(x)                                                  \
    static const BIGNUM ossl_bignum_##x = {                            \
        .data = (OSSL_FN *)&ossl_fn_static_##x##_storage.fn,           \
        .d = (BN_ULONG *)ossl_fn_static_##x##_storage.fixed.d,         \
        .top = (int)ossl_fn_static_##x##_sig_limbs,                    \
        .dmax = (int)OSSL_NELEM(ossl_fn_static_##x##_storage.fixed.d), \
        .flags = BN_FLG_STATIC_DATA,                                   \
    }

HEADER

# ---- Curve structs and OSSL_FN/BIGNUM constants ----
for my $name (@canonical) {
    my $c = $curves{$name};
    my $cname = sanitize($name);
    my $plen = $c->{param_len};
    my $nbits = $plen * 8;
    my @fields = ('p', 'a', 'b', 'x', 'y', 'order');
    my $guard = $c->{fips} ? 0 : 1;
    my $seed_hex = $c->{seed} // '';
    my $seed_len = length($seed_hex) / 2;
    my $field_type = ($c->{field} eq 'char2')
        ? 'NID_X9_62_characteristic_two_field'
        : 'NID_X9_62_prime_field';
    my @extra = @{ $c->{extra} // [] };
    my $nfields = 6 + scalar @extra;

    for my $hex ((map { $c->{$_} } @fields), @extra) {
        die "$name: field is not $plen bytes (padded hex expected)\n"
            if length($hex) != 2 * $plen;
    }

    $output .= "#ifndef FIPS_MODULE\n" if $guard;
    $output .= "/* $name */\n";

    # The curve struct; the data array is seed + p, a, b, x, y, order,
    # plus any extra fields (e.g. Montgomery RR values)
    $output .= "static const struct {\n";
    $output .= "    EC_CURVE_DATA h;\n";
    $output .= "    unsigned char data[$seed_len + $plen * $nfields];\n";
    $output .= "} _EC_$cname = {\n";
    $output .= "    { $field_type, $seed_len, $plen, $c->{cofactor} },\n";
    $output .= "    {\n";
    $output .= emit_bytes($seed_hex . join('', map { $c->{$_} } @fields)
                          . join '', @extra);
    $output .= " }\n};\n\n";

    # OSSL_FN storage and BIGNUM views
    for my $f (@fields, 'cof') {
        my $nlimbs = ($f eq 'cof') ? 1 : "OSSL_FN_LIMBS_N($nbits)";
        $output .= "OSSL_FN_STATIC_DECLARE(${cname}_${f}, $nlimbs);\n";
    }
    $output .= "\n";
    for my $f (@fields) {
        my $hex = $c->{$f};
        my @limbs = hex_to_limbs($hex);
        $output .= "OSSL_FN_STATIC_DEFINE(${cname}_${f}, OSSL_FN_LIMBS_N($nbits),\n";
        for my $i (0 .. $#limbs) {
            my $sep = ($i < $#limbs) ? ',' : ');';
            $output .= "    $limbs[$i]$sep\n";
        }
        $output .= "/* significant limbs for the BIGNUM top field */\n";
        $output .= "#define ossl_fn_static_${cname}_${f}_sig_limbs "
            . 'OSSL_FN_LIMBS_N(' . sig_bits($hex) . ")\n\n";
    }
    my $cof = $c->{cofactor};
    $output .= "/* $name cofactor == $cof */\n";
    $output .= "OSSL_FN_STATIC_DEFINE(${cname}_cof, 1, $cof);\n";
    $output .= "#define ossl_fn_static_${cname}_cof_sig_limbs "
        . 'OSSL_FN_LIMBS_N(' . sig_bits(sprintf '%X', $cof) . ")\n\n";
    for my $f (@fields, 'cof') {
        $output .= "make_ec_bn(${cname}_${f});\n";
    }
    $output .= "#endif /* FIPS_MODULE */\n" if $guard;
    $output .= "\n";
}

# ---- Static BIGNUM lookup table ----
$output .= "static const struct {\n";
$output .= "    int nid;\n";
$output .= "    EC_STATIC_BIGNUM bn;\n";
$output .= "} ec_static_curves[] = {\n";
for my $name (@enabled) {
    my ($cname, $c) = resolve($name);
    my $csym = sanitize($cname);
    my $nid = 'NID_' . sanitize($name);
    my $guard = $c->{fips} ? 0 : 1;

    $output .= "#ifndef FIPS_MODULE\n" if $guard;
    $output .= "    { $nid,\n";
    $output .= "        { &ossl_bignum_${csym}_p,\n";
    $output .= "            &ossl_bignum_${csym}_a,\n";
    $output .= "            &ossl_bignum_${csym}_b,\n";
    $output .= "            &ossl_bignum_${csym}_x,\n";
    $output .= "            &ossl_bignum_${csym}_y,\n";
    $output .= "            &ossl_bignum_${csym}_order,\n";
    $output .= "            &ossl_bignum_${csym}_cof } },\n";
    $output .= "#endif /* FIPS_MODULE */\n" if $guard;
}
$output .= "};\n\n";

# ---- curve_list[] tables ----
sub emit_table_entry {
    my ($name) = @_;
    my ($cname, $c) = resolve($name);
    my $csym = sanitize($cname);
    my $nid = 'NID_' . sanitize($name);
    my $method = exists $c->{method} ? "ec_method_$c->{method}" : '0';
    my $comment = $curves{$name}{comment} // '';

    return "    { $nid, &_EC_$csym.h, $method,\n"
        . "        \"" . c_string($comment) . "\" },\n";
}

$output .= "#ifdef FIPS_MODULE\n";
$output .= "static const ec_list_element curve_list[] = {\n";
for my $name (@canonical) {
    next unless $curves{$name}{fips};
    $output .= emit_table_entry($name);
}
$output .= "};\n";
$output .= "#else\n";
$output .= "static const ec_list_element curve_list[] = {\n";
for my $name (@enabled) {
    $output .= emit_table_entry($name);
}
$output .= "};\n";
$output .= "#endif /* FIPS_MODULE */\n\n";

# ---- Lookup function ----
$output .= <<'LOOKUP';
static int ec_static_lookup(int nid, const EC_STATIC_BIGNUM **out)
{
    size_t i;

    for (i = 0; i < OSSL_NELEM(ec_static_curves); i++)
        if (ec_static_curves[i].nid == nid) {
            *out = &ec_static_curves[i].bn;
            return 1;
        }
    return 0;
}
LOOKUP

print $output;
