#!/bin/sh

PERL="$1"

if test "$OSTYPE" = msdosdjgpp; then
    PATH="../apps\;$PATH"
else
    PATH="../apps:$PATH"
fi
export PATH

SSLEAY_CONFIG="-config CAss.cnf"
export SSLEAY_CONFIG

OPENSSL="`pwd`/../util/opensslwrap.sh"
export OPENSSL

/bin/rm -fr demoCA
OPENSSL_CONFIG=/dev/null $PERL ../apps/CA.pl -newca <<EOF
EOF

if [ $? != 0 ]; then
	exit 1;
fi

SSLEAY_CONFIG="-config Uss.cnf"
export SSLEAY_CONFIG
$PERL ../apps/CA.pl -newreq
if [ $? != 0 ]; then
	exit 1;
fi


SSLEAY_CONFIG="-config ../apps/openssl.cnf"
export SSLEAY_CONFIG
$PERL ../apps/CA.pl -sign  <<EOF
y
y
EOF
if [ $? != 0 ]; then
	exit 1;
fi


$PERL ../apps/CA.pl -verify newcert.pem
if [ $? != 0 ]; then
	exit 1;
fi

/bin/rm -fr demoCA newcert.pem newreq.pem
