#!/bin/sh

cmd='../util/shlib_wrap.sh ../apps/openssl x509'

if [ "$1"x != "x" ]; then
	t=$1
else
	t=testx509.pem
fi

echo testing X509 conversions
cp $t x509-fff.p

echo "p -> d"
$cmd -in x509-fff.p -inform p -outform d >x509-f.d || exit 1
echo "p -> p"
$cmd -in x509-fff.p -inform p -outform p >x509-f.p || exit 1

echo "d -> d"
$cmd -in x509-f.d -inform d -outform d >x509-ff.d1 || exit 1
echo "p -> d"
$cmd -in x509-f.p -inform p -outform d >x509-ff.d3 || exit 1

echo "d -> p"
$cmd -in x509-f.d -inform d -outform p >x509-ff.p1 || exit 1
echo "p -> p"
$cmd -in x509-f.p -inform p -outform p >x509-ff.p3 || exit 1

cmp x509-fff.p x509-f.p || exit 1
cmp x509-fff.p x509-ff.p1 || exit 1
cmp x509-fff.p x509-ff.p3 || exit 1

cmp x509-f.p x509-ff.p1 || exit 1
cmp x509-f.p x509-ff.p3 || exit 1

/bin/rm -f x509-f.* x509-ff.* x509-fff.*
exit 0
