/*
 * Copyright 2021 The OpenSSL Project Authors. All Rights Reserved.
 *
 * Licensed under the Apache License 2.0 (the "License").  You may not use
 * this file except in compliance with the License.  You can obtain a copy
 * in the file LICENSE in the source distribution or at
 * https://www.openssl.org/source/license.html
 */

#include <stdio.h>
#include <openssl/asn1t.h>
#include <openssl/x509.h>
#include <openssl/x509v3.h>
#include "x509_acert.h"

/*
 * OpenSSL ASN.1 template translation of RFC 5755 4.1.
 */

ASN1_SEQUENCE(OBJECT_DIGEST_INFO) = {
    ASN1_SIMPLE(OBJECT_DIGEST_INFO, digestedObjectType, ASN1_ENUMERATED),
    ASN1_OPT(OBJECT_DIGEST_INFO, otherObjectTypeID, ASN1_OBJECT),
    ASN1_SIMPLE(OBJECT_DIGEST_INFO, digestAlgorithm, X509_ALGOR),
    ASN1_SIMPLE(OBJECT_DIGEST_INFO, objectDigest, ASN1_BIT_STRING),
} ASN1_SEQUENCE_END(OBJECT_DIGEST_INFO)

ASN1_SEQUENCE(ISSUER_SERIAL) = {
    ASN1_SEQUENCE_OF(ISSUER_SERIAL, issuer, GENERAL_NAME),
    ASN1_EMBED(ISSUER_SERIAL, serial, ASN1_INTEGER),
    ASN1_OPT(ISSUER_SERIAL, issuerUID, ASN1_BIT_STRING),
} ASN1_SEQUENCE_END(ISSUER_SERIAL)

ASN1_SEQUENCE(ACERT_ISSUER_V2FORM) = {
    ASN1_SEQUENCE_OF_OPT(ACERT_ISSUER_V2FORM, issuerName, GENERAL_NAME),
    ASN1_IMP_OPT(ACERT_ISSUER_V2FORM, baseCertificateId, ISSUER_SERIAL, 0),
    ASN1_IMP_OPT(ACERT_ISSUER_V2FORM, objectDigestInfo, OBJECT_DIGEST_INFO, 1),
} ASN1_SEQUENCE_END(ACERT_ISSUER_V2FORM)

ASN1_CHOICE(ACERT_ISSUER) = {
    ASN1_SEQUENCE_OF(ACERT_ISSUER, u.v1Form, GENERAL_NAME),
    ASN1_IMP(ACERT_ISSUER, u.v2Form, ACERT_ISSUER_V2FORM, 0),
} ASN1_CHOICE_END(ACERT_ISSUER)

ASN1_SEQUENCE(HOLDER) = {
    ASN1_IMP_OPT(HOLDER, baseCertificateID, ISSUER_SERIAL, 0),
    ASN1_IMP_SEQUENCE_OF_OPT(HOLDER, entityName, GENERAL_NAME, 1),
    ASN1_IMP_OPT(HOLDER, objectDigestInfo, OBJECT_DIGEST_INFO, 2),
} ASN1_SEQUENCE_END(HOLDER)

ASN1_SEQUENCE(X509_ACERT_INFO) = {
    ASN1_EMBED(X509_ACERT_INFO, version, ASN1_INTEGER),
    ASN1_EMBED(X509_ACERT_INFO, holder, HOLDER),
    ASN1_EMBED(X509_ACERT_INFO, issuer, ACERT_ISSUER),
    ASN1_EMBED(X509_ACERT_INFO, signature, X509_ALGOR),
    ASN1_EMBED(X509_ACERT_INFO, serialNumber, ASN1_INTEGER),
    ASN1_EMBED(X509_ACERT_INFO, validityPeriod, X509_VAL),
    ASN1_SEQUENCE_OF(X509_ACERT_INFO, attributes, X509_ATTRIBUTE),
    ASN1_OPT(X509_ACERT_INFO, issuerUID, ASN1_BIT_STRING),
    ASN1_SEQUENCE_OF_OPT(X509_ACERT_INFO, extensions, X509_EXTENSION),
} ASN1_SEQUENCE_END(X509_ACERT_INFO)

ASN1_SEQUENCE(X509_ACERT) = {
    ASN1_SIMPLE(X509_ACERT, acinfo, X509_ACERT_INFO),
    ASN1_EMBED(X509_ACERT, sig_alg, X509_ALGOR),
    ASN1_EMBED(X509_ACERT, signature, ASN1_BIT_STRING),
} ASN1_SEQUENCE_END(X509_ACERT)

IMPLEMENT_ASN1_FUNCTIONS(X509_ACERT)
IMPLEMENT_ASN1_FUNCTIONS(X509_ACERT_INFO)
IMPLEMENT_ASN1_FUNCTIONS(ISSUER_SERIAL)
IMPLEMENT_ASN1_FUNCTIONS(OBJECT_DIGEST_INFO)
IMPLEMENT_ASN1_FUNCTIONS(ACERT_ISSUER_V2FORM)
