=pod

=head1 NAME

BN_jacobi_symbol - Calculate the Jacobi symbol

=head1 SYNOPSIS

 #include <openssl/bn.h>

 int BN_jacobi_symbol(const BIGNUM *a, const BIGNUM *b, BN_CTX *ctx);

=head1 DESCRIPTION

BN_jacobi_symbol() calculates the Jacobi symbol (B<a> / B<b>).
The parameter B<b> should be a positive odd number.

The parameter B<ctx> should be previously allocated using L<BN_CTX_new(3)>
or B<NULL>.

=head1 RETURN VALUES

On success it returns -1, 0 or 1. On error it returns -2.

=head1 HISTORY

BN_jacobi_symbol() was added in 1.1.x.

=head1 COPYRIGHT

Copyright 2018 The OpenSSL Project Authors. All Rights Reserved.

Licensed under the OpenSSL license (the "License").  You may not use
this file except in compliance with the License.  You can obtain a copy
in the file LICENSE in the source distribution or at
L<https://www.openssl.org/source/license.html>.

=cut
