=pod

=head1 NAME

ISSUER_SIGN_TOOL_new, ISSUER_SIGN_TOOL_free,ISSUER_SIGN_TOOL_it,
d2i_ISSUER_SIGN_TOOL, i2d_ISSUER_SIGN_TOOL

=head1 SYNOPSIS

=for openssl generic

 #include <openssl/x509v3.h>

 extern const ISSUER_SIGN_TOOL_it;

 ISSUER_SIGN_TOOL *ISSUER_SIGN_TOOL_new(void);
 void ISSUER_SIGN_TOOL_free(ISSUER_SIGN_TOOL *v);

 ISSUER_SIGN_TOOL *d2i_ISSUER_SIGN_TOOL(ISSUER_SIGN_TOOL **a, const unsigned char **pp, long length);
 int i2d_ISSUER_SIGN_TOOL(const ISSUER_SIGN_TOOL *a, unsigned char **pp);

=head1 DESCRIPTION

The ISSUER_SIGN_TOOL_new() function returns a new ISSUER_SIGN_TOOL.

ISSUER_SIGN_TOOL_free() frees up a single ISSUER_SIGN_TOOL object.

=head1 RETURN VALUES

ISSUER_SIGN_TOOL_new() returns a newly created ISSUER_SIGN_TOOL or NULL if the call fails.

ISSUER_SIGN_TOOL_free() does not return values.

d2i_ISSUER_SIGN_TOOL() and i2d_ISSUER_SIGN_TOOL() decode and encode an B<ISSUER_SIGN_TOOL>
structure. They otherwise follow the conventions of other ASN.1 functions such as d2i_X509().

=head1 HISTORY

The ISSUER_SIGN_TOOL_up_ref(), ISSUER_SIGN_TOOL_lock() and ISSUER_SIGN_TOOL_unlock()
functions were added in OpenSSL 3.0.

=head1 COPYRIGHT

Copyright 2020 The OpenSSL Project Authors. All Rights Reserved.

Licensed under the Apache License 2.0 (the "License").  You may not use
this file except in compliance with the License.  You can obtain a copy
in the file LICENSE in the source distribution or at
L<https://www.openssl.org/source/license.html>.

=cut
