=pod

=head1 NAME

OBJ_NAME_do_all, OBJ_NAME_do_all_sorted
- iterate over all registered objects of a given type

=head1 SYNOPSIS

 #include <openssl/objects.h>

 void OBJ_NAME_do_all(int type, void (*fn)(const OBJ_NAME *, void *arg),
                      void *arg);
 void OBJ_NAME_do_all_sorted(int type,
                             void (*fn)(const OBJ_NAME *, void *arg),
                             void *arg);

=head1 DESCRIPTION

OBJ_NAME_do_all() calls the function I<fn> for each entry in the object name
table of the specified I<type>.
The I<arg> parameter is passed to I<fn> along with each OBJ_NAME entry.

OBJ_NAME_do_all_sorted() is similar to OBJ_NAME_do_all() but the entries
are sorted alphabetically by name before the callback is invoked.

The I<type> parameter specifies which category of names to iterate over.
The following types are defined:

=over 4

=item B<OBJ_NAME_TYPE_MD_METH>

Message digest methods.

=item B<OBJ_NAME_TYPE_CIPHER_METH>

Cipher methods.

=item B<OBJ_NAME_TYPE_PKEY_METH>

Public key methods.

=item B<OBJ_NAME_TYPE_COMP_METH>

Compression methods.

=item B<OBJ_NAME_TYPE_MAC_METH>

MAC methods.

=item B<OBJ_NAME_TYPE_KDF_METH>

KDF methods.

=back

The B<OBJ_NAME> structure passed to the callback contains the following fields:

=over 4

=item I<type>

The type of the object (one of the B<OBJ_NAME_TYPE_*> constants).

=item I<name>

The name of the object.

=item I<alias>

An integer flag indicating whether this entry is an alias. Set to
B<OBJ_NAME_ALIAS> (0x8000) if this is an alias, 0 otherwise. When this is an
alias, the I<data> field contains the name that the alias resolves to.

=item I<data>

Implementation-specific data associated with the object.

=back

=head1 THREAD SAFETY

These functions are B<not> thread-safe with respect to modifications of the
object name table.
They must not be called concurrently with OBJ_NAME_add(), OBJ_NAME_remove(),
or OBJ_NAME_cleanup().
Applications should ensure appropriate synchronization when using these
functions in a multi-threaded environment where the object name table may
be modified.

=head1 RETURN VALUES

These functions do not return a value.

=head1 SEE ALSO

L<OBJ_nid2obj(3)>,
L<EVP_get_cipherbyname(3)>,
L<EVP_get_digestbyname(3)>

=head1 HISTORY

These functions were added in OpenSSL 0.9.6a.

=head1 COPYRIGHT

Copyright 2026 The OpenSSL Project Authors. All Rights Reserved.

Licensed under the Apache License 2.0 (the "License").  You may not use
this file except in compliance with the License.  You can obtain a copy
in the file LICENSE in the source distribution or at
L<https://www.openssl.org/source/license.html>.

=cut
