=pod

=head1 NAME

OPENSSL_gmtime, OPENSSL_gmtime_adj, OPENSSL_gmtime_diff,
OPENSSL_time_t_compare - platform-agnostic OpenSSL time routines

=head1 SYNOPSIS

 #include <openssl/crypto.h>

 struct tm *OPENSSL_gmtime(const time_t *timer, struct tm *result);
 int OPENSSL_gmtime_adj(struct tm *tm, int offset_day, long offset_sec);
 int OPENSSL_gmtime_diff(int *pday, int *psec,
                        const struct tm *from, const struct tm *to);
 int OPENSSL_time_t_compare(time_t a, time_t a_offset,
                            time_t b, time_t b_offset);

=head1 DESCRIPTION

OPENSSL_gmtime() returns the UTC time specified by B<timer> into the provided
B<result> argument.

OPENSSL_gmtime_adj() adds the offsets in B<offset_day> and B<offset_sec> to B<tm>.

OPENSSL_gmtime_diff() calculates the difference between B<from> and B<to>.

OPENSSL_time_t_compare() is a time_t-safe comparison function with offsets.

=head1 NOTES

It is an error to call OPENSSL_gmtime() with B<result> equal to NULL. The
contents of the time_t given by B<timer> are stored into the B<result>. Calling
with B<timer> equal to NULL means use the current time.

OPENSSL_gmtime_adj() converts B<tm> into a days and seconds value, adds the
offsets, then converts back into a B<struct tm> specified by B<tm>. Leap seconds
are not considered.

OPENSSL_gmtime_diff() calculates the difference between the two B<struct tm>
structures B<from> and B<to>. The difference in days is placed into B<pday>,
the remaining seconds are placed to B<psec>. The value in B<psec> will be less
than the number of seconds per day (3600). Leap seconds are not considered.

OPENSSL_time_t_compare() compares two time_t values with corresponding offsets.
The comparison is the equivalent to:

=over 4

B<a> + B<a_offset> <=> B<b> + B<b_offset>

=back

The calculation is done using signed 64-bit integers. If either B<a>+B<a_offset> or
B<b>+B<b_offset> exceed the value of a signed 64-bit integer, the results will be
system-dependent.

=head1 RETURN VALUES

OPENSSL_gmtime() returns NULL on error, or B<result> on success.

OPENSSL_gmtime_adj() and OPENSSL_gmtime_diff() return 0 on error, and 1 on success.

OPENSSL_time_t_compare() returns -1 if B<a>+B<a_offset> is less than B<b>+B<b_offset>,
0 if B<a>+B<a_offset> equals B<b>+B<b_offset>, and
1 if B<a>+B<a_offset> is greater than B<b>+B<b_offset>.

=head1 HISTORY

OPENSSL_time_t_compare() is new in OpenSSL 3.1.
OPENSSL_gmtime(), OPENSSL_gmtime_adj() and OPENSSL_gmtime_diff() have been
in OpenSSL since 1.0.0.

=head1 COPYRIGHT

Copyright 2022 The OpenSSL Project Authors. All Rights Reserved.

Licensed under the Apache License 2.0 (the "License").  You may not use
this file except in compliance with the License.  You can obtain a copy
in the file LICENSE in the source distribution or at
L<https://www.openssl.org/source/license.html>.

=cut
