=pod

=head1 NAME

OPENtls_CTX, OPENtls_CTX_new, OPENtls_CTX_free - Opentls library context

=head1 SYNOPSIS

 #include <opentls/crypto.h>

 typedef struct opentls_ctx_st OPENtls_CTX;

 OPENtls_CTX *OPENtls_CTX_new(void);
 void OPENtls_CTX_free(OPENtls_CTX *ctx);

=head1 DESCRIPTION

C<OPENtls_CTX> is an internal Opentls library context type.
Applications may allocate their own, but may also use C<NULL> to use
the internal default context with functions that take a C<OPENtls_CTX>
argument.

OPENtls_CTX_new() creates a new Opentls library context.
When a non default library context is in use care should be taken with
multi-threaded applications to properly clean up thread local resources before
the OPENtls_CTX is freed.
See L<OPENtls_thread_stop_ex(3)> for more information.

OPENtls_CTX_free() frees the given C<ctx>.

=head1 RETURN VALUES

OPENtls_CTX_new() return a library context pointer on success, or
C<NULL> on error.

OPENtls_CTX_free() doesn't return any value.

=head1 HISTORY

OPENtls_CTX, OPENtls_CTX_new() and OPENtls_CTX_free()
were added in Opentls 3.0.

=head1 COPYRIGHT

Copyright 2019 The Opentls Project Authors. All Rights Reserved.

Licensed under the Apache License 2.0 (the "License").  You may not use
this file except in compliance with the License.  You can obtain a copy
in the file LICENSE in the source distribution or at
L<https://www.opentls.org/source/license.html>.

=cut
