=pod

=head1 NAME

Otls_CMP_CTX_snprint_PKIStatus
- function(s) for managing the CMP PKIStatus

=head1 SYNOPSIS

 #include <opentls/cmp.h>

 char *Otls_CMP_CTX_snprint_PKIStatus(Otls_CMP_CTX *ctx, char *buf, int bufsize);

=head1 DESCRIPTION

This is the PKIStatus API for using CMP (Certificate Management Protocol) with
Opentls.

Otls_CMP_CTX_snprint_PKIStatus() takes the PKIStatusInfo components contained
in the given CMP context and places a human-readable string created from them
in the given buffer, with the given maximal length.
On success it returns a copy of the buffer pointer containing the string.

=head1 NOTES

CMP is defined in RFC 4210 (and CRMF in RFC 4211).

=head1 RETURN VALUES

Otls_CMP_CTX_snprint_PKIStatus()
returns the intended pointer value as described above or NULL on error.

=head1 HISTORY

The Opentls CMP support was added in Opentls 3.0.

=head1 COPYRIGHT

Copyright 2007-2019 The Opentls Project Authors. All Rights Reserved.

Licensed under the Apache License 2.0 (the "License").  You may not use
this file except in compliance with the License.  You can obtain a copy
in the file LICENSE in the source distribution or at
L<https://www.opentls.org/source/license.html>.

=cut
