=pod

=head1 NAME

RAND_egd, RAND_egd_bytes, RAND_query_egd_bytes - query entropy gathering daemon

=head1 SYNOPSIS

 #include <openssl/rand.h>

 int RAND_egd_bytes(const char *path, int num);
 int RAND_egd(const char *path);

 int RAND_query_egd_bytes(const char *path, unsigned char *buf, int num);

=head1 DESCRIPTION

Prior to OpenSSL 1.1.1, these functions could be used to query
an Entropy Gathering Daemon (EGD) over a local
socket to obtain randomness and seed the OpenSSL RNG.
The protocol used is defined by the EGDs available at
L<http://egd.sourceforge.net/> or L<http://prngd.sourceforge.net>.

OpenSSL can be configured at build time to try to use the EGD for seeding
automatically and this capability is no longer needed.

RAND_egd_bytes() and RAND_egd() return an error.

RAND_query_egd_bytes() is equivalent to calling RAND_bytes() if B<buf>
is not NULL.  If B<buf> is NULL, it returns an error.

=head1 RETURN VALUES

RAND_egd() and RAND_egd_bytes() return -1.

RAND_query_egd_bytes() returns what RAND_bytes() returns.

=head1 SEE ALSO

L<RAND_bytes(3)>

=head1 COPYRIGHT

Copyright 2000-2018 The OpenSSL Project Authors. All Rights Reserved.

Licensed under the OpenSSL license (the "License").  You may not use
this file except in compliance with the License.  You can obtain a copy
in the file LICENSE in the source distribution or at
L<https://www.openssl.org/source/license.html>.

=cut
