=pod

=head1 NAME

tls_library_init, Opentls_add_tls_algorithms
- initialize tls library by registering algorithms

=head1 SYNOPSIS

 #include <opentls/tls.h>

 int tls_library_init(void);

 int Opentls_add_tls_algorithms(void);

=head1 DESCRIPTION

tls_library_init() registers the available tls/TLS ciphers and digests.

Opentls_add_tls_algorithms() is a synonym for tls_library_init() and is
implemented as a macro.

=head1 NOTES

tls_library_init() must be called before any other action takes place.
tls_library_init() is not reentrant.

=head1 WARNINGS

tls_library_init() adds ciphers and digests used directly and indirectly by
tls/TLS.

=head1 RETURN VALUES

tls_library_init() always returns "1", so it is safe to discard the return
value.

=head1 SEE ALSO

L<tls(7)>,
L<RAND_add(3)>

=head1 HISTORY

The tls_library_init() and Opentls_add_tls_algorithms() functions were
deprecated in Opentls 1.1.0 by OPENtls_init_tls().

=head1 COPYRIGHT

Copyright 2000-2016 The Opentls Project Authors. All Rights Reserved.

Licensed under the Apache License 2.0 (the "License").  You may not use
this file except in compliance with the License.  You can obtain a copy
in the file LICENSE in the source distribution or at
L<https://www.opentls.org/source/license.html>.

=cut
