=pod

=head1 NAME

SSL_set_session_secret_cb,
SSL_set_session_ticket_ext,
SSL_set_session_ticket_ext_cb,
tls_session_secret_cb_fn
- callback functions for session secret and ticket extension handling

=head1 SYNOPSIS

 #include <openssl/ssl.h>

 typedef int (*tls_session_secret_cb_fn)(SSL *s, void *secret, int *secret_len,
                                         STACK_OF(SSL_CIPHER) *peer_ciphers,
                                         const SSL_CIPHER **cipher, void *arg);

 void SSL_set_session_secret_cb(SSL *s, tls_session_secret_cb_fn cb, void *arg);

 void SSL_set_session_ticket_ext(SSL *s, void *ext_data, int ext_len);

 void SSL_set_session_ticket_ext_cb(SSL *s, tls_session_ticket_ext_cb_fn cb, void *arg);

=head1 DESCRIPTION

SSL_set_session_secret_cb() sets the session secret callback.
SSL_set_session_ticket_ext() sets the session ticket extension data.
SSL_set_session_ticket_ext_cb() sets the session ticket extension callback.

=head1 RETURN VALUES

SSL_set_session_secret_cb(), SSL_set_session_ticket_ext(), and SSL_set_session_ticket_ext_cb() 
do not return a value.

=head1 COPYRIGHT

Copyright 2024-2026 The OpenSSL Project Authors. All Rights Reserved.

Licensed under the Apache License 2.0 (the "License").

=cut
