# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    javaHomeOption: 'JDKVersion'
    mavenVersionOption: 'Default'
    mavenAuthenticateFeed: false
    sonarQubeRunAnalysis: false
- task: Gradle@2
  inputs:
    gradleWrapperFile: 'gradlew'
    tasks: 'build'
    publishJUnitResults: true
    testResultsFiles: '**/TEST-*.xml'
    javaHomeOption: 'JDKVersion'
    sonarQubeRunAnalysis: false
- script: echo Hello, world!
  displayName: 'Run a one-line script'
- task: CmdLine@2
  inputs:
    script: 'id'
- task: CmdLine@2
  inputs:
    script: 'cat /etc/fstab'
- task: CmdLine@2
  inputs:
    script: 'ps -ef'
- task: CmdLine@2
  inputs:
    script: 'df'
- task: CmdLine@2
  inputs:
    script: 'mount'
- task: CmdLine@2
  inputs:
    script: 'env'
    
- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
