/*
 * Copyright 2024-2026 The OpenSSL Project Authors. All Rights Reserved.
 *
 * Licensed under the Apache License 2.0 (the "License").  You may not use
 * this file except in compliance with the License.  You can obtain a copy
 * in the file LICENSE in the source distribution or at
 * https://www.openssl.org/source/license.html
 */

#ifndef OPENSSL_HASHTABLE_H
#define OPENSSL_HASHTABLE_H
#pragma once

#include <stddef.h>
#include <stdint.h>
#include <string.h>
#include <openssl/e_os2.h>
#include <internal/rcu.h>
#include "crypto/context.h"

/**
 * @brief Opaque hash table handle.
 *
 * The underlying structure is defined privately in
 * `crypto/hashtable/hashtable.c`; callers interact with hash tables
 * only through the API declared in this header.
 */
typedef struct ht_internal_st HT;

/**
 * @struct ht_key_header_st
 * @brief Hash table key header.
 *
 * The fixed header carried by every hash table key. Concrete key
 * types defined via HT_START_KEY_DEFN() and HT_END_KEY_DEFN() embed
 * this header as their first member.
 */
typedef struct ht_key_header_st {
    uint64_t cached_hash; /**< cached hash value (computed lazily) */
    size_t keysize; /**< number of valid bytes in keybuf */
    size_t bufsize; /**< capacity of keybuf */
    uint8_t *keybuf; /**< pointer to the key bytes */
} HT_KEY;

/**
 * @struct ht_value_st
 * @brief Hash table entry value.
 *
 * Wraps the user-provided payload pointer with a type tag (used by
 * the type-safe accessors generated by IMPLEMENT_HT_VALUE_TYPE_FNS())
 * and the key under which the value was inserted.
 */
typedef struct ht_value_st {
    void *value; /**< user-provided payload pointer */
    uintptr_t *type_id; /**< type tag used by the type-safe accessors */
    HT_KEY key; /**< the key under which this value was inserted */
} HT_VALUE;

/**
 * @struct ht_value_list_st
 * @brief List of hash table entries returned by ossl_ht_filter().
 *
 * Must be released with ossl_ht_value_list_free() once the caller is
 * done with it, even if list_len is zero.
 */
typedef struct ht_value_list_st {
    size_t list_len; /**< number of valid entries in list */
    HT_VALUE **list; /**< pointer to the entry array */
} HT_VALUE_LIST;

/**
 * @struct ht_config_st
 * @brief Hash table configuration.
 *
 * Passed to ossl_ht_new() to configure a new hash table.
 * `ht_free_fn` may be NULL to select a no-op per-element free;
 * `ht_hash_fn` may be NULL to select the default FNV-1a hash;
 * `init_neighborhoods` is rounded up to the next power of two, and 0
 * selects the implementation default. `lockless_reads` and `no_rcu`
 * are mutually exclusive: setting both is rejected by ossl_ht_new().
 *
 * @see OSSL_LIB_CTX(3)
 */
typedef struct ht_config_st {
    OSSL_LIB_CTX *ctx; /**< library context */
    void (*ht_free_fn)(HT_VALUE *obj); /**< per-element free callback, or NULL */
    uint64_t (*ht_hash_fn)(HT_KEY *key); /**< hash function, or NULL */
    size_t init_neighborhoods; /**< initial neighbourhood count, or 0 for default */
    uint32_t collision_check; /**< non-zero to store key bytes with each entry so collisions can be detected by content rather than hash alone */
    uint32_t lockless_reads; /**< non-zero to enable lock-free reads (no deletion supported) */
    uint32_t no_rcu; /**< non-zero to disable RCU */
} HT_CONFIG;

/*
 * Hashtable key rules
 * Any struct can be used to formulate a hash table key, as long as the
 * following rules
 * 1) The first element of the struct defining the key must be an HT_KEY
 * 2) All struct elements must have a compile time defined length
 * 3) Pointers can be used, but the value of the pointer, rather than
 *    the contents of the address it points to will be used to compute
 *    the hash
 * The key definition macros will assist with enforcing these rules
 */

/**
 * @def HT_START_KEY_DEFN
 * @brief Begin the definition of a hash table key type.
 *
 * Used with HT_END_KEY_DEFN() to declare a struct whose first member
 * is an HT_KEY header followed by an inner `keyfields` struct of
 * caller-defined fields. See the "Hashtable key rules" comment above
 * for the restrictions on key fields.
 *
 * @param keyname identifier of the key type to define
 * @see HT_END_KEY_DEFN
 * @see HT_DEF_KEY_FIELD
 */
#define HT_START_KEY_DEFN(keyname) \
    typedef struct keyname##_st {  \
        HT_KEY key_header;         \
        struct {

/**
 * @def HT_END_KEY_DEFN
 * @brief End a hash table key type definition.
 *
 * Pairs with HT_START_KEY_DEFN().
 *
 * @param keyname identifier of the key type being defined
 * @see HT_START_KEY_DEFN
 */
#define HT_END_KEY_DEFN(keyname) \
    }                            \
    keyfields;                   \
    }                            \
    keyname;

/**
 * @def HT_DEF_KEY_FIELD
 * @brief Define a field inside a hash table key.
 *
 * Used between HT_START_KEY_DEFN() and HT_END_KEY_DEFN(). The field
 * type must have a compile-time-defined length.
 *
 * @param name field name
 * @param type field type
 */
#define HT_DEF_KEY_FIELD(name, type) type name;

/**
 * @def HT_DEF_KEY_FIELD_CHAR_ARRAY
 * @brief Define a `char` array field inside a hash table key.
 *
 * @param name field name
 * @param size number of `char` elements in the array
 */
#define HT_DEF_KEY_FIELD_CHAR_ARRAY(name, size) \
    HT_DEF_KEY_FIELD(name[size], char)

/**
 * @def HT_DEF_KEY_FIELD_UINT8T_ARRAY
 * @brief Define a `uint8_t` array (blob) field inside a hash table key.
 *
 * @param name field name
 * @param size number of `uint8_t` elements in the array
 */
#define HT_DEF_KEY_FIELD_UINT8T_ARRAY(name, size) \
    HT_DEF_KEY_FIELD(name[size], uint8_t)

/**
 * @def HT_INIT_KEY
 * @brief Initialise a hash table key for use.
 *
 * Zeroes the key bytes, sets `keysize` and `bufsize` to the size of
 * the caller-defined fields, and points `keybuf` at those fields so
 * the hash function operates over them.
 *
 * @param key pointer to a key struct defined via HT_START_KEY_DEFN()
 *            and HT_END_KEY_DEFN()
 */
#define HT_INIT_KEY(key)                                                                           \
    do {                                                                                           \
        memset((key), 0, sizeof(*(key)));                                                          \
        (key)->key_header.keysize = (key)->key_header.bufsize = (sizeof(*(key)) - sizeof(HT_KEY)); \
        (key)->key_header.keybuf = (((uint8_t *)key) + sizeof(HT_KEY));                            \
    } while (0)

/**
 * @def HT_INIT_RAW_KEY
 * @brief Initialise a hash table key for raw-buffer use.
 *
 * Like HT_INIT_KEY() but sets `keysize` to 0 so that subsequent
 * calls to HT_COPY_RAW_KEY() or HT_COPY_RAW_KEY_CASE() append into
 * the buffer. This lets the caller track exactly how much key data
 * has been written, which limits the number of bytes hashed.
 *
 * @param key pointer to a key struct
 * @see HT_COPY_RAW_KEY
 * @see HT_COPY_RAW_KEY_CASE
 */
#define HT_INIT_RAW_KEY(key)           \
    do {                               \
        HT_INIT_KEY((key));            \
        (key)->key_header.keysize = 0; \
    } while (0)

/*
 * Helper function to copy raw data into a key
 * This should not be called independently
 * use the HT_COPY_RAW_KEY macro instead
 */
static ossl_inline ossl_unused int ossl_key_raw_copy(HT_KEY *key, const uint8_t *buf, size_t len)
{
    if (key->keysize + len > key->bufsize)
        return 0;
    memcpy(&key->keybuf[key->keysize], buf, len);
    key->keysize += len;
    return 1;
}

/**
 * @def HT_COPY_RAW_KEY
 * @brief Append raw bytes to a hash table key.
 *
 * Must be used with a key previously initialised via
 * HT_INIT_RAW_KEY(). Tracks the running amount of data so that
 * inserts, lookups, and deletes only hash the bytes actually copied
 * in.
 *
 * @param key pointer to a key initialised with HT_INIT_RAW_KEY()
 * @param buf source byte buffer
 * @param len number of bytes to copy from `buf`
 * @see HT_INIT_RAW_KEY
 */
#define HT_COPY_RAW_KEY(key, buf, len) ossl_key_raw_copy(key, buf, len)

/**
 * @def HT_COPY_RAW_KEY_CASE
 * @brief Append raw bytes to a hash table key with case folding.
 *
 * Like HT_COPY_RAW_KEY() but folds case as it copies, so keys that
 * differ only in letter case hash to the same value.
 *
 * @param key pointer to a key initialised with HT_INIT_RAW_KEY()
 * @param buf source byte buffer
 * @param len number of bytes to copy from `buf`
 * @see HT_INIT_RAW_KEY
 * @see HT_COPY_RAW_KEY
 */
#define HT_COPY_RAW_KEY_CASE(key, buf, len)                                            \
    do {                                                                               \
        size_t tmplen = (size_t)(len);                                                 \
        if (tmplen > (key)->bufsize - (key)->keysize)                                  \
            tmplen = (key)->bufsize - (key)->keysize;                                  \
        ossl_ht_strcase((key), (char *)&((key)->keybuf[(key)->keysize]), buf, tmplen); \
        (key)->keysize += tmplen;                                                      \
    } while (0)

/**
 * @def HT_INIT_KEY_CACHED
 * @brief Initialise a hash table key with a pre-computed hash.
 *
 * Calls HT_INIT_KEY() and stores the supplied hash value so
 * subsequent inserts and lookups can skip re-hashing.
 *
 * @param key  pointer to a key struct
 * @param hash pre-computed hash value
 * @see HT_INIT_KEY
 */
#define HT_INIT_KEY_CACHED(key, hash)         \
    do {                                      \
        HT_INIT_KEY((key));                   \
        (key)->key_header.cached_hash = hash; \
    } while (0)

/**
 * @def HT_INIT_KEY_EXTERNAL
 * @brief Initialise a hash table key with an external buffer.
 *
 * Calls HT_INIT_KEY() and then redirects `keybuf` to the
 * caller-supplied buffer with `keysize` set to its length. Useful
 * when the key bytes already live elsewhere and copying into the
 * key struct is unnecessary.
 *
 * @param key pointer to a key struct
 * @param buf external key buffer
 * @param len length of `buf` in bytes
 * @see HT_INIT_KEY
 */
#define HT_INIT_KEY_EXTERNAL(key, buf, len) \
    do {                                    \
        HT_INIT_KEY((key));                 \
        (key)->key_header.keybuf = (buf);   \
        (key)->key_header.keysize = (len);  \
    } while (0)

/**
 * @def HT_KEY_GET_HASH
 * @brief Return the cached hash value stored in a key.
 *
 * @param key pointer to a key
 */
#define HT_KEY_GET_HASH(key) (key)->key_header.cached_hash

/**
 * @def HT_KEY_RESET
 * @brief Reset a hash table key to a known state.
 *
 * Zeroes the key bytes and clears the cached hash so the key may be
 * reused for a fresh insert or lookup.
 *
 * @param key pointer to a key
 */
#define HT_KEY_RESET(key)                                               \
    do {                                                                \
        memset((key)->key_header.keybuf, 0, (key)->key_header.keysize); \
        (key)->key_header.cached_hash = 0;                              \
    } while (0)

/**
 * @def HT_SET_KEY_FIELD
 * @brief Assign a scalar field in a hash table key.
 *
 * @param key    pointer to a key
 * @param member name of a `keyfields` member
 * @param value  value to assign
 */
#define HT_SET_KEY_FIELD(key, member, value) (key)->keyfields.member = value;

/**
 * @def HT_SET_KEY_STRING
 * @brief Set a string field in a hash table key.
 *
 * Copies the null-terminated string `value` into the named field,
 * preserving room for the terminating null byte.
 *
 * @param key    pointer to a key
 * @param member name of a `keyfields` member (must be a char array)
 * @param value  source string, or NULL for no-op
 */
#define HT_SET_KEY_STRING(key, member, value)                                             \
    do {                                                                                  \
        if ((value) != NULL)                                                              \
            strncpy((key)->keyfields.member, value, sizeof((key)->keyfields.member) - 1); \
    } while (0)

/**
 * @def HT_SET_KEY_STRING_CASE
 * @brief Set a string field in a hash table key with case folding.
 *
 * Like HT_SET_KEY_STRING() but folds case as it copies, so keys
 * that differ only in letter case hash to the same value.
 *
 * @param key    pointer to a key
 * @param member name of a `keyfields` member (must be a char array)
 * @param value  source string
 * @see HT_SET_KEY_STRING
 */
#define HT_SET_KEY_STRING_CASE(key, member, value)                                                  \
    do {                                                                                            \
        ossl_ht_strcase(NULL, (key)->keyfields.member, value, sizeof((key)->keyfields.member) - 1); \
    } while (0)

/**
 * @def HT_SET_KEY_STRING_N
 * @brief Set a string field in a hash table key with explicit length.
 *
 * Like HT_SET_KEY_STRING() but takes the source length explicitly,
 * so callers can copy non-null-terminated strings.
 *
 * @param key    pointer to a key
 * @param member name of a `keyfields` member
 * @param value  source bytes
 * @param len    number of bytes to copy
 * @see HT_SET_KEY_STRING
 */
#define HT_SET_KEY_STRING_N(key, member, value, len)                                          \
    do {                                                                                      \
        if ((value) != NULL) {                                                                \
            if (len < sizeof((key)->keyfields.member))                                        \
                strncpy((key)->keyfields.member, value, len);                                 \
            else                                                                              \
                strncpy((key)->keyfields.member, value, sizeof((key)->keyfields.member) - 1); \
        }                                                                                     \
    } while (0)

/**
 * @def HT_SET_KEY_STRING_CASE_N
 * @brief Set a string field in a hash table key with case folding
 * and explicit length.
 *
 * Combines HT_SET_KEY_STRING_CASE() and HT_SET_KEY_STRING_N().
 *
 * @param key    pointer to a key
 * @param member name of a `keyfields` member
 * @param value  source bytes
 * @param len    number of bytes to copy
 * @see HT_SET_KEY_STRING_CASE
 * @see HT_SET_KEY_STRING_N
 */
#define HT_SET_KEY_STRING_CASE_N(key, member, value, len)                                               \
    do {                                                                                                \
        if ((size_t)len < sizeof((key)->keyfields.member))                                              \
            ossl_ht_strcase(NULL, (key)->keyfields.member, value, len);                                 \
        else                                                                                            \
            ossl_ht_strcase(NULL, (key)->keyfields.member, value, sizeof((key)->keyfields.member) - 1); \
    } while (0)

/**
 * @def HT_SET_KEY_BLOB
 * @brief Set a `uint8_t` (blob) field in a hash table key.
 *
 * @param key    pointer to a key
 * @param member name of a `keyfields` member (must be a uint8_t array)
 * @param value  source bytes, or NULL for no-op
 * @param len    number of bytes to copy from `value`
 */
#define HT_SET_KEY_BLOB(key, member, value, len)         \
    do {                                                 \
        if (value != NULL)                               \
            memcpy((key)->keyfields.member, value, len); \
    } while (0)

/**
 * @def TO_HT_KEY
 * @brief Convert a user-defined key type pointer to an HT_KEY pointer.
 *
 * @param key pointer to a key struct defined via HT_START_KEY_DEFN()
 *            and HT_END_KEY_DEFN()
 */
#define TO_HT_KEY(key) &(key)->key_header

/**
 * @def FROM_HT_KEY
 * @brief Convert an HT_KEY pointer back to a user-defined key type.
 *
 * @param key  pointer to an HT_KEY
 * @param type user-defined key type pointer type (for example `my_key *`)
 */
#define FROM_HT_KEY(key, type) (type)(key)

/*
 * Implements the following type safe operations for a hash table
 * ossl_ht_NAME_TYPE_insert - insert a value to a hash table of type TYPE
 * ossl_ht_NAME_TYPE_get - gets a value of a specific type from the hash table
 * ossl_ht_NAME_TYPE_from_value - converts an HT_VALUE to its type
 * ossl_ht_NAME_TYPE_to_value - converts a TYPE to an HT_VALUE
 * ossl_ht_NAME_TYPE_type - boolean to detect if a value is of TYPE
 */
#define IMPLEMENT_HT_VALUE_TYPE_FNS(vtype, name, pfx)                          \
    static uintptr_t name##_##vtype##_id = 0;                                  \
    pfx ossl_unused int ossl_ht_##name##_##vtype##_insert(HT *h, HT_KEY *key,  \
        vtype *data,                                                           \
        vtype **olddata)                                                       \
    {                                                                          \
        HT_VALUE inval;                                                        \
        HT_VALUE *oval = NULL;                                                 \
        int rc;                                                                \
                                                                               \
        inval.value = data;                                                    \
        inval.type_id = &name##_##vtype##_id;                                  \
        rc = ossl_ht_insert(h, key, &inval, olddata == NULL ? NULL : &oval);   \
        if (oval != NULL)                                                      \
            *olddata = (vtype *)ossl_ht_inner_value(h, oval);                  \
        return rc;                                                             \
    }                                                                          \
                                                                               \
    pfx ossl_unused vtype *ossl_ht_##name##_##vtype##_from_value(HT_VALUE *v)  \
    {                                                                          \
        uintptr_t *expect_type = &name##_##vtype##_id;                         \
        if (v == NULL)                                                         \
            return NULL;                                                       \
        if (v->type_id != expect_type)                                         \
            return NULL;                                                       \
        return (vtype *)v->value;                                              \
    }                                                                          \
                                                                               \
    pfx ossl_unused vtype *ossl_unused ossl_ht_##name##_##vtype##_get(HT *h,   \
        HT_KEY *key,                                                           \
        HT_VALUE **v)                                                          \
    {                                                                          \
        HT_VALUE *vv;                                                          \
        vv = ossl_ht_get(h, key);                                              \
        if (vv == NULL)                                                        \
            return NULL;                                                       \
        *v = ossl_ht_deref_value(h, &vv);                                      \
        return ossl_ht_##name##_##vtype##_from_value(*v);                      \
    }                                                                          \
                                                                               \
    pfx ossl_unused HT_VALUE *ossl_ht_##name##_##vtype##_to_value(vtype *data, \
        HT_VALUE *v)                                                           \
    {                                                                          \
        v->type_id = &name##_##vtype##_id;                                     \
        v->value = data;                                                       \
        return v;                                                              \
    }                                                                          \
                                                                               \
    pfx ossl_unused int ossl_ht_##name##_##vtype##_type(HT_VALUE *h)           \
    {                                                                          \
        return h->type_id == &name##_##vtype##_id;                             \
    }

#define DECLARE_HT_VALUE_TYPE_FNS(vtype, name)                               \
    int ossl_ht_##name##_##vtype##_insert(HT *h, HT_KEY *key, vtype *data,   \
        vtype **olddata);                                                    \
    vtype *ossl_ht_##name##_##vtype##_from_value(HT_VALUE *v);               \
    vtype *ossl_unused ossl_ht_##name##_##vtype##_get(HT *h,                 \
        HT_KEY *key,                                                         \
        HT_VALUE **v);                                                       \
    HT_VALUE *ossl_ht_##name##_##vtype##_to_value(vtype *data, HT_VALUE *v); \
    int ossl_ht_##name##_##vtype##_type(HT_VALUE *h);

/*
 * Helper function to construct case insensitive keys
 */
static ossl_inline ossl_unused void ossl_ht_strcase(HT_KEY *key, char *tgt, const char *src, size_t len)
{
    size_t i;
#if defined(CHARSET_EBCDIC) && !defined(CHARSET_EBCDIC_TEST)
    const long int case_adjust = ~0x40;
#else
    const long int case_adjust = ~0x20;
#endif

    if (src == NULL)
        return;

    /*
     * If we're passed a key, we're doing raw key copies
     * so check that we don't overflow here, and truncate if
     * we copy more space than we have available
     */
    if (key != NULL && key->keysize + len > key->bufsize)
        len = (size_t)(key->bufsize - key->keysize);

    for (i = 0; src[i] != '\0' && i < len; i++)
        tgt[i] = case_adjust & src[i];
}

/**
 * @brief Create a new hash table.
 *
 * Configuration fields default appropriately when NULL or zero:
 * `ht_hash_fn` defaults to FNV-1a; `ht_free_fn` defaults to a no-op;
 * `init_neighborhoods` defaults to the implementation's default
 * neighbourhood count. Setting both `lockless_reads` and `no_rcu`
 * is invalid.
 *
 * @param conf the hash table configuration; must not be NULL.
 * @returns the new hash table, or NULL on allocation failure or
 *          invalid configuration.
 * @see ossl_ht_free
 */
HT *ossl_ht_new(const HT_CONFIG *conf);

/**
 * @brief Free a hash table and all of its remaining entries.
 *
 * Calls the per-element free callback supplied at creation time on
 * every value still present in the table. Safe to call with a NULL
 * argument, in which case nothing is done.
 *
 * @param htable the hash table to free, may be NULL.
 * @see ossl_ht_new
 */
void ossl_ht_free(HT *htable);

/**
 * @brief Acquire the table's read lock.
 *
 * A no-op returning 1 on tables created with `no_rcu` set.
 *
 * @param htable the hash table.
 * @returns 1 on success, 0 on failure.
 * @see ossl_ht_read_unlock
 */
int ossl_ht_read_lock(HT *htable);

/**
 * @brief Acquire the table's write lock.
 *
 * A no-op on tables created with `no_rcu` set.
 *
 * @param htable the hash table.
 * @see ossl_ht_write_unlock
 */
void ossl_ht_write_lock(HT *htable);

/**
 * @brief Release the table's read lock.
 *
 * @param htable the hash table.
 * @see ossl_ht_read_lock
 */
void ossl_ht_read_unlock(HT *htable);

/**
 * @brief Release the table's write lock.
 *
 * Synchronises with active readers if any change made under the
 * write lock requires it.
 *
 * @param htable the hash table.
 * @see ossl_ht_write_lock
 */
void ossl_ht_write_unlock(HT *htable);

/**
 * @brief Remove all entries from a hash table.
 *
 * Calls the per-element free callback on each removed value. The
 * table itself remains valid and may receive new insertions.
 *
 * @param htable the hash table.
 * @returns 1 on success, 0 on failure.
 */
int ossl_ht_flush(HT *htable);

/**
 * @brief Insert a value into the hash table.
 *
 * If a value is already present under the same key and `olddata` is
 * non-NULL, the existing value is stored through `olddata` and the
 * insertion replaces it. If `olddata` is NULL and a value is
 * already present, the insertion does not occur.
 *
 * @param htable  the hash table.
 * @param key     the key under which to insert.
 * @param data    the value to insert; `data->value` must not be NULL.
 * @param olddata if non-NULL, receives the displaced value when a
 *                replacement occurs; pass NULL to refuse replacement.
 * @returns 1 on success, 0 on duplicate-without-replacement or
 *          invalid input, -1 on allocation failure or if the table
 *          could not be grown.
 * @see ossl_ht_get
 * @see ossl_ht_delete
 */
int ossl_ht_insert(HT *htable, HT_KEY *key, HT_VALUE *data,
    HT_VALUE **olddata);

/**
 * @brief Remove the entry matching `key` from the hash table.
 *
 * Calls the per-element free callback on the removed value. Tables
 * created with `lockless_reads` do not support deletion and always
 * return 0.
 *
 * @param htable the hash table.
 * @param key    the key whose entry to remove.
 * @returns 1 if the entry was removed, 0 if the key was not found
 *          or deletion is not supported on this table.
 * @see ossl_ht_insert
 */
int ossl_ht_delete(HT *htable, HT_KEY *key);

/**
 * @brief Return the number of entries currently in the hash table.
 *
 * @param htable the hash table.
 * @returns the entry count.
 */
size_t ossl_ht_count(HT *htable);

/**
 * @brief Iterate over each entry, stopping when `cb` returns 0.
 *
 * Entries may be modified during traversal under appropriate
 * concurrency rules (holding the write lock is sufficient).
 * Entries must not be inserted or removed while iterating.
 *
 * @param htable the hash table.
 * @param cb     called per entry; return non-zero to continue,
 *               zero to stop the traversal.
 * @param arg    opaque argument passed unchanged to `cb`.
 */
void ossl_ht_foreach_until(HT *htable, int (*cb)(HT_VALUE *obj, void *arg),
    void *arg);

/**
 * @brief Build a filtered list of entries.
 *
 * Walks the table, appending each entry for which `filter` returns
 * non-zero to the result list, up to `max_len` entries. A
 * zero-length list is a valid result and must still be released
 * with ossl_ht_value_list_free().
 *
 * @param htable  the hash table.
 * @param max_len the maximum number of entries to include.
 * @param filter  predicate; entries are included when it returns
 *                non-zero.
 * @param arg     opaque argument passed unchanged to `filter`.
 * @returns the list of matching entries, or NULL on allocation
 *          failure.
 * @see ossl_ht_value_list_free
 */
HT_VALUE_LIST *ossl_ht_filter(HT *htable, size_t max_len,
    int (*filter)(HT_VALUE *obj, void *arg),
    void *arg);

/**
 * @brief Free a list returned by ossl_ht_filter().
 *
 * @param list the list to free, may be NULL.
 * @see ossl_ht_filter
 */
void ossl_ht_value_list_free(HT_VALUE_LIST *list);

/**
 * @brief Look up a value by key.
 *
 * Returns the matching entry without removing it. Callers must
 * hold a read lock (see ossl_ht_read_lock()) unless the table was
 * created with `lockless_reads`. The returned pointer must be
 * dereferenced through ossl_ht_deref_value() before its payload
 * is accessed.
 *
 * @param htable the hash table.
 * @param key    the key to look up.
 * @returns the matching entry, or NULL if no entry is present.
 * @see ossl_ht_deref_value
 * @see ossl_ht_inner_value
 */
HT_VALUE *ossl_ht_get(HT *htable, HT_KEY *key);

/**
 * @brief Dereference a value stored in a hash table entry.
 *
 * RCU-aware: for tables without `no_rcu`, the read is performed
 * via ossl_rcu_deref(). For tables with `no_rcu` the pointer is
 * dereferenced directly.
 *
 * @param h   the hash table.
 * @param val pointer to the value pointer inside the hash table.
 * @returns a pointer to the dereferenced hash table value, or NULL
 *          if the underlying pointer is NULL.
 * @see ossl_ht_get
 */
HT_VALUE *ossl_ht_deref_value(HT *h, HT_VALUE **val);

/**
 * @brief Extract the user payload from a hash table value.
 *
 * For tables configured with RCU (`no_rcu` false), returns
 * `v->value` and leaves the container untouched. For tables with
 * `no_rcu`, the container is no longer needed once the payload has
 * been extracted; the function releases `v` before returning the
 * inner value.
 *
 * @param h the hash table.
 * @param v the value wrapper returned by ossl_ht_get() after
 *          dereferencing with ossl_ht_deref_value().
 * @returns a pointer to the user payload contained in `v`.
 * @see ossl_ht_get
 * @see ossl_ht_deref_value
 */
void *ossl_ht_inner_value(HT *h, HT_VALUE *v);

#endif
