=pod

=head1 NAME

ossl-guide-migration, migration_guide
- OpenSSL Guide: Migrating from older OpenSSL versions

=head1 SYNOPSIS

See the individual manual pages for details.

=head1 DESCRIPTION

This guide details the changes required to migrate to new versions of OpenSSL.
Currently this covers OpenSSL 4.0. For earlier versions refer to
L<https://docs.openssl.org/3.6/man7/ossl-guide-migration/>.
For an overview of some of the key concepts introduced in OpenSSL 4.0 see
L<crypto(7)>.

=head1 OPENSSL 4.0

=head2 Main Changes from OpenSSL 3.X

Remove this text when we start filling in data about removal

=head1 HISTORY

The migration guide was created for OpenSSL 4.0.

=head1 COPYRIGHT

Copyright 2021-2025 The OpenSSL Project Authors. All Rights Reserved.

Licensed under the Apache License 2.0 (the "License").  You may not use
this file except in compliance with the License.  You can obtain a copy
in the file LICENSE in the source distribution or at
L<https://www.openssl.org/source/license.html>.

=cut
