=pod

=head1 NAME

password handling - How diverse parts of OpenSSL treat pass phrases

=head1 DESCRIPTION

=head2 The general case

In a modern world with all sorts of character encodings, the treatment of pass
phrases has become increasingly complex.

The OpenSSL library doesn't treat pass phrases in any special way as a general
rule, and trusts the application or user to choose a suitable character set
and stick to that throughout the life of affected objects.
This means that for an object that was encrypted using a pass phrase encoded in
ISO-8859-1, that object needs to be decrypted using a pass phrase encoded in
ISO-8859-1.
Anything else will have the decryption fail.

=head2 PKCS#12

PKCS#12 is a bit different regarding pass phrase encoding.
The standard stipulates that the pass phrase shall be encoded as a BMPString,
i.e. UTF-16.

OpenSSL tries to adapt to this requirements in one of the following manners:

=over 4

=item 1.

Tries to read the pass phrase as UTF-8 and re-encode that to UTF-16, or failing
that...

=item 2.

Assumes that the pass phrase is encoded in ASCII or ISO-8859-X and
opportunistically prepends each byte with a zero byte and uses the result
as a BMPString.

=back

Note that historical OpenSSL versions did variant 2 only, and that is the
reason why OpenSSL still does this, to be able to read files produced with
older versions.

It should be noted that this approach isn't entirely fault free.
A passphrase encoded in ISO-8859-X could very well have a sequence such as
0xC3 0xAF (which is the two characters "LATIN CAPITAL LETTER A WITH TILDE"
and "MACRON" in ISO-8859-1 encoding), but would be misunterpreted as the
perfectly valid UTF-8 encoded U+00EF (LATIN SMALL LETTER I WITH DIARESIS).

=head2 OSSL_STORE

L<ossl_store(7)> acts as a general interface to access all kinds of
objects, potentially protected with a pass phrase, a PIN or something else.
This API currently doesn't stipulate any specific encoding of pass phrases,
but uses the underlying routines with their behaviours.
This means that the pass phrase to unlock a PKCS#12 file will be treated as
described for PKCS#12 above, and the pass phrase for a PEM files will be
treated as the general case described above.
Note that this applies only to the 'file' scheme loader, other loaders will
have their own behaviours.

=head1 CONCLUSIONS

TBA

=head1 SEE ALSO

L<PKCS12_parse(3)>,
L<ossl_store(7)>,
TBA

=head1 COPYRIGHT

Copyright 2018 The OpenSSL Project Authors. All Rights Reserved.

Licensed under the OpenSSL license (the "License").  You may not use
this file except in compliance with the License.  You can obtain a copy
in the file LICENSE in the source distribution or at
L<https://www.openssl.org/source/license.html>.

=cut
