/*
 * Copyright 1995-2017 The OpenSSL Project Authors. All Rights Reserved.
 *
 * Licensed under the OpenSSL license (the "License").  You may not use
 * this file except in compliance with the License.  You can obtain a copy
 * in the file LICENSE in the source distribution or at
 * https://www.openssl.org/source/license.html
 */

#ifndef HEADER_CNG_ERR_H
# define HEADER_CNG_ERR_H

# ifdef  __cplusplus
extern "C" {
# endif

/* BEGIN ERROR CODES */
/*
 * The following lines are auto generated by the script mkerr.pl. Any changes
 * made after this point may be overwritten when the script is next run.
 */

static int ERR_load_CNG_strings(void);
static void ERR_unload_CNG_strings(void);
static void ERR_CNG_error(int function, int reason, char *file, int line);
# define CNGerr(f,r) ERR_CNG_error((f),(r),OPENSSL_FILE,OPENSSL_LINE)

/* Error codes for the CNG functions. */

/* Function codes. */
# define CNG_F_ACCUMULATE_SYSTEM_STORES                   100
# define CNG_F_BIND_CNG                                   101
# define CNG_F_CNG_GET_PKEY                               104
# define CNG_F_CNG_STORE_ENUM_CERTS_INIT                  117
# define CNG_F_CNG_STORE_ENUM_CERTS_LOAD                  118
# define CNG_F_CNG_STORE_ENUM_KEYS_INIT                   115
# define CNG_F_CNG_STORE_ENUM_KEYS_LOAD                   116
# define CNG_F_CNG_STORE_ENUM_PROVIDERS_INIT              110
# define CNG_F_CNG_STORE_ENUM_PROVIDERS_LOAD              111
# define CNG_F_CNG_STORE_ENUM_STORES_INIT                 112
# define CNG_F_CNG_STORE_ENUM_STORES_LOAD                 113
# define CNG_F_CNG_STORE_GET_KEYS_INIT                    105
# define CNG_F_CNG_STORE_GET_KEYS_LOAD                    106
# define CNG_F_CNG_STORE_LOAD                             114
# define CNG_F_CNG_STORE_NEW                              107
# define CNG_F_CNG_STORE_OPEN                             102
# define CNG_F_ENUM_CERTS                                 103
# define CNG_F_TO_ASC                                     108
# define CNG_F_TO_WIDE                                    109

/* Reason codes. */
# define CNG_R_BAD_URL_ENCODING                           112
# define CNG_R_BIND_FAILED                                119
# define CNG_R_CERTGETCERTIFICATECONTEXTPROPERTY_ERROR    124
# define CNG_R_CERTOPENSTORE_ERROR                        125
# define CNG_R_DUPLICATE_KEY                              100
# define CNG_R_EMPTY_KEY                                  101
# define CNG_R_EMPTY_URI                                  102
# define CNG_R_EMPTY_VALUE                                103
# define CNG_R_FAILED_OPENING_STORE                       104
# define CNG_R_INIT_FAILED                                105
# define CNG_R_MULTIBYTETOWIDECHAR_ERROR                  120
# define CNG_R_NCRYPTENUMKEYS_ERROR                       123
# define CNG_R_NCRYPTENUMSTORAGEPROVIDERS_ERROR           122
# define CNG_R_NCRYPTEXPORTKEY_ERROR                      114
# define CNG_R_NCRYPTOPENKEY_ERROR                        115
# define CNG_R_NCRYPTOPENSTORAGEPROVIDER_ERROR            116
# define CNG_R_NOT_YET_SUPPORTED                          113
# define CNG_R_SYSTEM_STORE_ENUMERATION_FAILED            106
# define CNG_R_TEMPORARLY_UNSUPPORTED_KEY_TYPE            117
# define CNG_R_UNASSIGNED_KEY                             107
# define CNG_R_UNKNOWN_KEY                                108
# define CNG_R_UNSUPPORTED_KEY_TYPE                       118
# define CNG_R_URI_AUTHORITY_UNSUPPORED                   109
# define CNG_R_URI_FRAGMENT_UNSUPPORED                    110
# define CNG_R_URI_QUERY_UNSUPPORED                       111
# define CNG_R_WIDECHARTOMULTIBYTE_ERROR                  121

# ifdef  __cplusplus
}
# endif
#endif
