/*
 * Generated by util/mkerr.pl DO NOT EDIT
 * Copyright 1995-2021 The OpenSSL Project Authors. All Rights Reserved.
 *
 * Licensed under the OpenSSL license (the "License").  You may not use
 * this file except in compliance with the License.  You can obtain a copy
 * in the file LICENSE in the source distribution or at
 * https://www.openssl.org/source/license.html
 */

#include <openssl/err.h>
#include "e_kctl_err.h"

#ifndef OPENSSL_NO_ERR

static ERR_STRING_DATA KCTL_str_functs[] = {
    {ERR_PACK(0, KCTL_F_HW_RSA_PRIV_FUNC, 0), "kctl_hw_rsa_priv_func"},
    {ERR_PACK(0, KCTL_F_HW_RSA_PUB_FUNC, 0), "kctl_hw_rsa_pub_func"},
    {ERR_PACK(0, KCTL_F_KCTL_DH_GENERATE_KEY, 0), "kctl_dh_generate_key"},
    {ERR_PACK(0, KCTL_F_KCTL_DH_GENERATE_PRIV, 0), "kctl_dh_generate_priv"},
    {ERR_PACK(0, KCTL_F_KCTL_GET_DH_METHODS, 0), "kctl_get_DH_methods"},
    {ERR_PACK(0, KCTL_F_KCTL_PKEY_ADD, 0), "kctl_pkey_add"},
    {ERR_PACK(0, KCTL_F_KCTL_RSA_PRIV_DEC, 0), "kctl_rsa_priv_dec"},
    {ERR_PACK(0, KCTL_F_KCTL_RSA_PRIV_ENC, 0), "kctl_rsa_priv_enc"},
    {ERR_PACK(0, KCTL_F_KCTL_RSA_PUB_DEC, 0), "kctl_rsa_pub_dec"},
    {ERR_PACK(0, KCTL_F_KCTL_RSA_PUB_ENC, 0), "kctl_rsa_pub_enc"},
    {ERR_PACK(0, KCTL_F_KCTL_UPLOAD_DH_PAYLOAD, 0), "kctl_upload_dh_payload"},
    {ERR_PACK(0, KCTL_F_KCTL_UPLOAD_RSA_PRIVKEY, 0), "kctl_upload_rsa_privkey"},
    {0, NULL}
};

static ERR_STRING_DATA KCTL_str_reasons[] = {
    {ERR_PACK(0, 0, KCTL_R_BN_LIB_ERR), "bn lib err"},
    {ERR_PACK(0, 0, KCTL_R_DH_COMPUTE_FALUIRE), "dh compute faluire"},
    {ERR_PACK(0, 0, KCTL_R_HW_PRIV_FUNC_FAILURE), "hw priv func failure"},
    {ERR_PACK(0, 0, KCTL_R_HW_PUB_FUNC_FAILURE), "hw pub func failure"},
    {ERR_PACK(0, 0, KCTL_R_INVALID_RSA_KEY), "invalid rsa key"},
    {ERR_PACK(0, 0, KCTL_R_KCTL_ALLOC_DH_METH_FAILURE),
    "kctl alloc dh meth failure"},
    {ERR_PACK(0, 0, KCTL_R_KCTL_INVALID_PAYLOAD), "kctl invalid payload"},
    {ERR_PACK(0, 0, KCTL_R_KCTL_SET_DH_METH_FAILURE),
    "kctl set dh meth failure"},
    {ERR_PACK(0, 0, KCTL_R_KEYCTL_ADD_FAILURE), "keyctl add failure"},
    {ERR_PACK(0, 0, KCTL_R_PADDING_CHECK_FAILED), "padding check failed"},
    {ERR_PACK(0, 0, KCTL_R_UNKNOWN_PADDING_TYPE), "unknown padding type"},
    {0, NULL}
};

#endif

static int lib_code = 0;
static int error_loaded = 0;

int ERR_load_KCTL_strings(void)
{
    if (lib_code == 0)
        lib_code = ERR_get_next_error_library();

    if (!error_loaded) {
#ifndef OPENSSL_NO_ERR
        ERR_load_strings(lib_code, KCTL_str_functs);
        ERR_load_strings(lib_code, KCTL_str_reasons);
#endif
        error_loaded = 1;
    }
    return 1;
}

void ERR_unload_KCTL_strings(void)
{
    if (error_loaded) {
#ifndef OPENSSL_NO_ERR
        ERR_unload_strings(lib_code, KCTL_str_functs);
        ERR_unload_strings(lib_code, KCTL_str_reasons);
#endif
        error_loaded = 0;
    }
}

void ERR_KCTL_error(int function, int reason, char *file, int line)
{
    if (lib_code == 0)
        lib_code = ERR_get_next_error_library();
    ERR_PUT_error(lib_code, function, reason, file, line);
}
