/* ====================================================================
 * Copyright (c) 1999-2016 The OpenSSL Project.  All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in
 *    the documentation and/or other materials provided with the
 *    distribution.
 *
 * 3. All advertising materials mentioning features or use of this
 *    software must display the following acknowledgment:
 *    "This product includes software developed by the OpenSSL Project
 *    for use in the OpenSSL Toolkit. (http://www.OpenSSL.org/)"
 *
 * 4. The names "OpenSSL Toolkit" and "OpenSSL Project" must not be used to
 *    endorse or promote products derived from this software without
 *    prior written permission. For written permission, please contact
 *    openssl-core@OpenSSL.org.
 *
 * 5. Products derived from this software may not be called "OpenSSL"
 *    nor may "OpenSSL" appear in their names without prior written
 *    permission of the OpenSSL Project.
 *
 * 6. Redistributions of any form whatsoever must retain the following
 *    acknowledgment:
 *    "This product includes software developed by the OpenSSL Project
 *    for use in the OpenSSL Toolkit (http://www.OpenSSL.org/)"
 *
 * THIS SOFTWARE IS PROVIDED BY THE OpenSSL PROJECT ``AS IS'' AND ANY
 * EXPRESSED OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
 * PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL THE OpenSSL PROJECT OR
 * ITS CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 * SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
 * NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
 * HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
 * STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED
 * OF THE POSSIBILITY OF SUCH DAMAGE.
 * ====================================================================
 *
 * This product includes cryptographic software written by Eric Young
 * (eay@cryptsoft.com).  This product includes software written by Tim
 * Hudson (tjh@cryptsoft.com).
 *
 */

/*
 * NOTE: this file was auto generated by the mkerr.pl script: any changes
 * made to it will be overwritten when the script next updates this file,
 * only reason strings will be preserved.
 */

#include <stdio.h>
#include <openssl/err.h>
#include <openssl/bp.h>

/* BEGIN ERROR CODES */
#ifndef OPENSSL_NO_ERR

# define ERR_FUNC(func) ERR_PACK(ERR_LIB_BP,func,0)
# define ERR_REASON(reason) ERR_PACK(ERR_LIB_BP,0,reason)

static ERR_STRING_DATA BP_str_functs[] = {
    {ERR_FUNC(BP_F_BP_GROUP_NEW), "BP_GROUP_new"},
    {ERR_FUNC(BP_F_BP_GROUP_SET_CURVE), "BP_GROUP_set_curve"},
    {ERR_FUNC(BP_F_G1_ELEM_NEW), "G1_ELEM_new"},
    {ERR_FUNC(BP_F_G2_ELEMS_MAKE_AFFINE), "G2_ELEMs_make_affine"},
    {ERR_FUNC(BP_F_G2_ELEMS_MUL), "G2_ELEMs_mul"},
    {ERR_FUNC(BP_F_G2_ELEM_ADD), "G2_ELEM_add"},
    {ERR_FUNC(BP_F_G2_ELEM_CMP), "G2_ELEM_cmp"},
    {ERR_FUNC(BP_F_G2_ELEM_DBL), "G2_ELEM_dbl"},
    {ERR_FUNC(BP_F_G2_ELEM_GET_AFFINE_COORDINATES),
     "G2_ELEM_get_affine_coordinates"},
    {ERR_FUNC(BP_F_G2_ELEM_IS_ON_CURVE), "G2_ELEM_is_on_curve"},
    {ERR_FUNC(BP_F_G2_ELEM_NEW), "G2_ELEM_new"},
    {ERR_FUNC(BP_F_G2_ELEM_OCT2POINT), "G2_ELEM_oct2point"},
    {ERR_FUNC(BP_F_G2_ELEM_POINT2OCT), "G2_ELEM_point2oct"},
    {ERR_FUNC(BP_F_G2_ELEM_SET_AFFINE_COORDINATES),
     "G2_ELEM_set_affine_coordinates"},
    {ERR_FUNC(BP_F_G2_WNAF_PRECOMPUTE_MULT), "g2_wNAF_precompute_mult"},
    {ERR_FUNC(BP_F_GT_ELEMS_PAIRING), "GT_ELEMs_pairing"},
    {ERR_FUNC(BP_F_GT_ELEM_ELEM2OCT), "GT_ELEM_elem2oct"},
    {ERR_FUNC(BP_F_GT_ELEM_NEW), "GT_ELEM_new"},
    {ERR_FUNC(BP_F_GT_ELEM_OCT2ELEM), "GT_ELEM_oct2elem"},
    {ERR_FUNC(BP_F_GT_FINAL_EXP), "GT_final_exp"},
    {ERR_FUNC(BP_F_GT_MILLER_ADD), "GT_miller_add"},
    {ERR_FUNC(BP_F_GT_MILLER_DBL), "GT_miller_dbl"},
    {ERR_FUNC(BP_F_GT_MILLER_FINAL), "GT_miller_final"},
    {0, NULL}
};

static ERR_STRING_DATA BP_str_reasons[] = {
    {ERR_REASON(BP_R_BUFFER_TOO_SMALL), "buffer too small"},
    {ERR_REASON(BP_R_INVALID_ARGUMENT), "invalid argument"},
    {ERR_REASON(BP_R_INVALID_PRIME_FIELD), "invalid prime field"},
    {ERR_REASON(BP_R_MALLOC_FAILURE), "malloc failure"},
    {ERR_REASON(BP_R_NOT_IMPLEMENTED), "not implemented"},
    {ERR_REASON(BP_R_PASSED_NULL_PARAMETER), "passed null parameter"},
    {ERR_REASON(BP_R_POINT_IS_NOT_ON_CURVE), "point is not on curve"},
    {ERR_REASON(BP_R_UNDEFINED_GENERATOR), "undefined generator"},
    {0, NULL}
};

#endif

void ERR_load_BP_strings(void)
{
#ifndef OPENSSL_NO_ERR

    if (ERR_func_error_string(BP_str_functs[0].error) == NULL) {
        ERR_load_strings(0, BP_str_functs);
        ERR_load_strings(0, BP_str_reasons);
    }
#endif
}
