#! /usr/bin/env perl
# Copyright 2026 The OpenSSL Project Authors. All Rights Reserved.
#
# Licensed under the Apache License 2.0 (the "License").  You may not use
# this file except in compliance with the License.  You can obtain a copy
# in the file LICENSE in the source distribution or at
# https://www.openssl.org/source/license.html

package OpenSSL::fipsparams;

use strict;
use warnings;
use Exporter;

our @ISA = qw(Exporter);
our @EXPORT_OK = qw(produce_fips_indicators produce_fips_selftest_params);

sub produce_fips_indicators {
    my @params = @_;
    my $s;
    open(local *STDOUT, '>', \$s);

    print "/* Machine generated by util/perl/OpenSSL/fipsparams.pm */\n";
    print "\n";
    print "typedef struct fips_indicators_st {\n";
    foreach my $p (@params) {
        printf "    const char *%s_string;\n", $p->[0];
        printf "    unsigned char %s_enabled;\n", $p->[0];
    }
    print "} FIPS_INDICATORS;\n";

    print "\n";
    print "static void init_fips_indicators(FIPS_INDICATORS *indicators)\n";
    print "{\n";
    foreach my $p (@params) {
        my $field = $p->[0];
        my $name = $p->[1];
        my $enabled = $p->[2];
        printf "    indicators->%s_string = \"%s\";\n", $field, $enabled;
        printf "    indicators->%s_enabled = %s;\n", $field, $enabled;
    }
    print "}\n";

    print "\n";
    print "static OSSL_PARAM *get_fips_indicator_params_from_core(\n";
    print "        OSSL_PARAM *op, FIPS_INDICATORS *fi)\n";
    print "{\n";
    foreach my $p (@params) {
        my $field = $p->[0];
        my $name  = $p->[1];
        print "    *op++ = OSSL_PARAM_construct_utf8_ptr(\n";
        printf "        $name, (char**)&fi->%s_string,\n", $field;
        printf "        sizeof(fi->%s_string));\n", $field;
    }
    print "    return op;\n";
    print "}\n";

    print "\n";
    print "#define OSSL_FIPS_INDICATOR_PARAM_TYPES \\\n";
    my $cnt = 0;
    foreach my $p (@params) {
        my $name  = $p->[1];
        print "    OSSL_PARAM_DEFN($name, OSSL_PARAM_INTEGER, NULL, 0)";
        print "," if ($cnt++ < $#params);
        print "\\\n";
    }
    print "\n";

    print "\n";
    print "static int get_fips_indicator_params(OSSL_PARAM *params, FIPS_INDICATORS *fi)\n";
    print "{\n";
    print "    OSSL_PARAM *p;\n";
    foreach my $p (@params) {
        my $field = $p->[0];
        my $name  = $p->[1];
        print "    p = OSSL_PARAM_locate(params, $name);\n";
        printf "    if (p != NULL && !OSSL_PARAM_set_int(p, fi->%s_enabled))\n", $field;
        print "        return 0;\n";
    }
    print "    return 1;\n";
    print "}\n";

    print "\n";
    print "static int set_fips_indicators_from_core(FIPS_INDICATORS *fi)\n";
    print "{\n";
    foreach my $p (@params) {
        my $field = $p->[0];
        printf "    if (fi->%s_string != NULL) {\n", $field;
        printf "        if (strcmp(fi->%s_string, \"1\") == 0)\n", $field;
        printf "            fi->%s_enabled = 1;\n", $field;
        printf "        else if (strcmp(fi->%s_string, \"0\") == 0)\n", $field;
        printf "            fi->%s_enabled = 0;\n", $field;
        print "        else\n";
        print "            return 0;\n";
        print "    }\n";
    }
    print "    return 1;\n";
    print "}\n";

    foreach my $p (@params) {
        my $field = $p->[0];
        print "\n";
        printf "int ossl_fips_config_%s(OSSL_LIB_CTX *libctx)\n", $field;
        print "{\n";
        print "    FIPS_GLOBAL *fgbl = ossl_lib_ctx_get_data(libctx, OSSL_LIB_CTX_FIPS_PROV_INDEX);\n";
        print "    FIPS_INDICATORS *indicators = get_fips_indicators(fgbl);\n";
        printf "    return indicators->%s_enabled;\n", $field;
        print "}\n";
    }

    return $s;
}

sub produce_fips_selftest_params {
    my @params = @_;
    my $s;
    open(local *STDOUT, '>', \$s);

    print "/* Machine generated by util/perl/OpenSSL/fipsparams.pm */\n";

    print "static OSSL_PARAM *get_fips_selftest_params_from_core(\n";
    print "        OSSL_PARAM *op, SELF_TEST_POST_PARAMS *stpp)\n";
    print "{\n";
    foreach my $p (@params) {
        my $field = $p->[0];
        my $name  = $p->[1];
        print "    *op++ = OSSL_PARAM_construct_utf8_ptr(\n";
        print "        $name, (char**)&stpp->$field,\n";
        print "        sizeof(stpp->$field));\n";
    }
    print "    return op;\n";
    print "}\n";

    return $s;
}
