
=pod

=head1 NAME

Crypto - OpenSSL Cryptography library

=head1 SYNOPSIS

=head1 DESCRIPTION

The OpenSSL B<crypto> library implements various cryptography standards
related to the Secure Sockets Layer (SSL v2/v3) and Transport Layer Security
(TLS v1) protocols. It provides a rich API which is documented here.

...

=head1 SEE ALSO

openssl(1), ssl(3)

=head1 HISTORY

The crypto(3) document appeared in OpenSSL 0.9.2

=cut

