#!/bin/sh
# Do a makedepend, only leave out the standard headers
# Written by Ben Laurie <ben@algroup.co.uk> 19 Jan 1999

TOP=$1
shift
if [ "$1" = "-MD" ]; then
    shift
    MAKEDEPEND=$1
    shift
fi
if [ "$MAKEDEPEND" = "" ]; then MAKEDEPEND=makedepend; fi

cp Makefile.ssl Makefile.save
if [ "$MAKEDEPEND" = "gcc" ]; then
    sed -e '/^# DO NOT DELETE.*/,$d' < Makefile.ssl > Makefile.tmp
    echo '# DO NOT DELETE THIS LINE -- make depend depends on it.' >> Makefile.tmp
    gcc -M $@ >> Makefile.tmp
    perl $TOP/util/clean-depend.pl < Makefile.tmp > Makefile.new
    #cat Makefile.tmp > Makefile.new
else
    ${MAKEDEPEND} -f Makefile.ssl $@
    perl $TOP/util/clean-depend.pl < Makefile.ssl > Makefile.new
fi
mv Makefile.new Makefile.ssl
