#! /usr/bin/env perl
# Copyright 2026 The OpenSSL Project Authors. All Rights Reserved.
#
# Licensed under the Apache License 2.0 (the "License").  You may not use
# this file except in compliance with the License.  You can obtain a copy
# in the file LICENSE in the source distribution or at
# https://www.openssl.org/source/license.html

# Emit include/libcms/names.h on standard output: one object-like macro
# per symbol the CMS sources define with external linkage, renaming it to
# the same name with the LIBCMS_ prefix.  The macros are only active when
# OSSL_LIBCMS_NAMES is defined.
#
# The public symbols come from util/libcms.num.  The internal ones are not
# recorded anywhere, so they are collected from the sources: the
# ossl_cms_*() functions from the headers that declare them, and the ASN.1
# items and functions the templates define, which the ASN.1 macros paste
# together from the type name.  A symbol missed here keeps the name
# libcrypto's copy of the same source uses, which shows up as a duplicate
# definition when both libraries are linked statically.

use strict;
use warnings;
use FindBin;

my $top = $ARGV[0] // "$FindBin::Bin/..";
my $numfile = "$top/util/libcms.num";
my %names;

open my $num, '<', $numfile or die "$numfile: $!\n";
while (<$num>) {
    s|\R$||;
    s|#.*||;
    next if /^\s*$/;
    my ($name) = split /\s+/;
    $names{$name} = 1;
}
close $num;

# Internal functions, from the headers that declare them.
foreach my $header ("$top/cms/cms_local.h", "$top/include/internal/cms.h") {
    open my $fh, '<', $header or die "$header: $!\n";
    while (<$fh>) {
        $names{$1} = 1 while /\b(ossl_cms_[A-Za-z0-9_]+)\s*\(/g;
    }
    close $fh;
}

# ASN.1 items and functions.  A template whose END macro is the static_
# form defines a static item, which cannot collide, so only the others
# matter.  The IMPLEMENT_ASN1_* macros define the encode and allocate
# functions for the same types.
foreach my $src (glob("$top/cms/*.c")) {
    open my $fh, '<', $src or die "$src: $!\n";
    while (<$fh>) {
        # Every template names its type in the _END macro, wherever the
        # formatting has put it.  Naming a static item too is harmless.
        $names{"$1_it"} = 1
            while /ASN1_(?:NDEF_)?(?:SEQUENCE|CHOICE|ITEM_TEMPLATE)_END(?:_cb)?\(([A-Za-z0-9_]+)/g;

        if (/^IMPLEMENT_ASN1_([A-Z_]+)\(([A-Za-z0-9_]+)/) {
            my ($what, $type) = ($1, $2);
            $names{"${type}_it"} = 1;
            $names{"${type}_new"} = $names{"${type}_free"} = 1
                unless $what eq 'ENCODE_FUNCTIONS';
            $names{"d2i_$type"} = $names{"i2d_$type"} = 1
                unless $what eq 'ALLOC_FUNCTIONS';
            $names{"${type}_dup"} = 1 if $what eq 'DUP_FUNCTION';
            next;
        }

        # Function definitions at file scope.  Only the external ones can
        # collide, and only those may be renamed: renaming something the
        # sources merely call would look for it under the wrong name.
        next if /^static\b/;
        $names{$1} = 1
            if /^[A-Za-z_][A-Za-z0-9_ ]*[ *]([A-Za-z_][A-Za-z0-9_]*)\(/;
    }
    close $fh;
}

print <<"_____";
/*
 * WARNING: do not edit!
 * Generated by util/mklibcmsnames.pl from util/libcms.num and the CMS
 * sources.
 *
 * Renames every symbol the CMS sources define with external linkage to
 * the same name with the LIBCMS_ prefix, so that libcms shares no symbol
 * with libcrypto's copy of the same sources.  The macros are only active
 * when OSSL_LIBCMS_NAMES is defined, which the libcms entry header does.
 *
 * Copyright 2026 The OpenSSL Project Authors. All Rights Reserved.
 *
 * Licensed under the Apache License 2.0 (the "License").  You may not use
 * this file except in compliance with the License.  You can obtain a copy
 * in the file LICENSE in the source distribution or at
 * https://www.openssl.org/source/license.html
 */

#if !defined(LIBCMS_NAMES_H)
#define LIBCMS_NAMES_H
#if defined(OSSL_LIBCMS_NAMES)
_____
foreach (sort keys %names) {
    printf "#define %-*s LIBCMS_%s\n", 45, $_, $_;
}
print <<"_____";
#endif /* defined(OSSL_LIBCMS_NAMES) */
#endif /* !defined(LIBCMS_NAMES_H) */
_____
