#! /usr/bin/env perl
# Copyright 2026 The OpenSSL Project Authors. All Rights Reserved.
#
# Licensed under the Apache License 2.0 (the "License").  You may not use
# this file except in compliance with the License.  You can obtain a copy
# in the file LICENSE in the source distribution or at
# https://www.openssl.org/source/license.html

# Emit libcmp_names.h on standard output: one object-like macro
# per symbol the CMP and CRMF sources define with external linkage,
# renaming it to the same name with the LIBCMP_ prefix.  The macros are
# only active when OSSL_LIBCMP_NAMES is defined.
#
# The public symbols come from util/libcmp.num.  The internal ones are not
# recorded anywhere, so they are collected from the sources: the
# ossl_cmp_*() and ossl_crmf_*() functions from the headers that declare
# them, and the ASN.1 items and functions the templates define, which the
# ASN.1 macros paste together from the type name.  A symbol missed here
# keeps the name libcrypto's copy of the same source uses, which shows up
# as a duplicate definition when both libraries are linked statically.

use strict;
use warnings;
use FindBin;

my $top = $ARGV[0] // "$FindBin::Bin/..";
my $numfile = "$top/util/libcmp.num";
my %names;

open my $num, '<', $numfile or die "$numfile: $!\n";
while (<$num>) {
    s|\R$||;
    s|#.*||;
    next if /^\s*$/;
    my ($name) = split /\s+/;
    $names{$name} = 1;
}
close $num;

# Internal functions, from the headers that declare them.  Some of those
# headers also define macros with names of the same shape; a macro has no
# symbol to rename, and renaming it here would collide with its own
# definition, so skip the preprocessor directives and what they continue
# onto.
foreach my $header ("$top/cmp/cmp_local.h", "$top/cmp/crmf_local.h",
                    "$top/include/internal/crmf.h") {
    open my $fh, '<', $header or die "$header: $!\n";
    my $in_directive = 0;
    while (<$fh>) {
        my $continues = m{\\\s*$};
        if ($in_directive || m{^\s*#}) {
            $in_directive = $continues;
            next;
        }
        $names{$1} = 1 while /\b(ossl_(?:cmp|crmf)_[A-Za-z0-9_]+)\s*\(/g;
    }
    close $fh;
}

# ASN.1 items and functions.  A template whose END macro is the static_
# form defines a static item, which cannot collide, so only the others
# matter.  The IMPLEMENT_ASN1_* macros define the encode and allocate
# functions for the same types.
foreach my $src (glob("$top/cmp/*.c")) {
    open my $fh, '<', $src or die "$src: $!\n";
    while (<$fh>) {
        # Every template names its type in the _END macro, wherever the
        # formatting has put it.  Naming a static item too is harmless.
        $names{"$1_it"} = 1
            while /ASN1_(?:NDEF_)?(?:SEQUENCE|CHOICE|ITEM_TEMPLATE)_END(?:_cb)?\(([A-Za-z0-9_]+)/g;

        if (/^IMPLEMENT_ASN1_([A-Z_]+)\(([A-Za-z0-9_]+)/) {
            my ($what, $type) = ($1, $2);
            $names{"${type}_it"} = 1;
            $names{"${type}_new"} = $names{"${type}_free"} = 1
                unless $what eq 'ENCODE_FUNCTIONS';
            $names{"d2i_$type"} = $names{"i2d_$type"} = 1
                unless $what eq 'ALLOC_FUNCTIONS';
            $names{"${type}_dup"} = 1 if $what eq 'DUP_FUNCTION';
            next;
        }

        # Function definitions at file scope.  Only the external ones can
        # collide, and only those may be renamed: renaming something the
        # sources merely call would look for it under the wrong name.
        next if /^static\b/;
        $names{$1} = 1
            if /^[A-Za-z_][A-Za-z0-9_ ]*[ *]([A-Za-z_][A-Za-z0-9_]*)\(/;
    }
    close $fh;
}

print <<"_____";
/*
 * WARNING: do not edit!
 * Generated by util/mklibcmpnames.pl from util/libcmp.num and the CMP and
 * CRMF sources.
 *
 * Renames every symbol those sources define with external linkage to the
 * same name with the LIBCMP_ prefix, so that libcmp shares no symbol with
 * libcrypto's copy of the same sources.  The macros are only active when
 * OSSL_LIBCMP_NAMES is defined, which the libcmp entry headers do.
 *
 * Copyright 2026 The OpenSSL Project Authors. All Rights Reserved.
 *
 * Licensed under the Apache License 2.0 (the "License").  You may not use
 * this file except in compliance with the License.  You can obtain a copy
 * in the file LICENSE in the source distribution or at
 * https://www.openssl.org/source/license.html
 */

#if !defined(OSSL_LIBCMP_NAMES_H)
#define OSSL_LIBCMP_NAMES_H
#if defined(OSSL_LIBCMP_NAMES)
_____
foreach (sort keys %names) {
    printf "#define %-*s LIBCMP_%s\n", 45, $_, $_;
}
print <<"_____";
#endif /* defined(OSSL_LIBCMP_NAMES) */
#endif /* !defined(OSSL_LIBCMP_NAMES_H) */
_____
