## -*- mode: perl; -*-
# Targets for cross-compiling to Windows (MSVC) on x86_64 or aarch64 using clang-cl
# on a Unix-like system.
#

my %targets = (
    "win64-cross-clang-cl" => {
        inherit_from     => [ "VC-WIN64-common" ],
        template         => 1,

        sys_id           => "WIN64A",

        build_scheme     => [ "unified", "unix" ],
        build_file       => "Makefile",

        perl_platform    => "Unix",
        msvc_syntax      => 1,

        CC               => "clang-cl",
        cflags           => add("-fuse-ld=lld-link"),

        AR               => "llvm-lib",
        RC               => "llvm-rc",

        def_extension    => '.def',
        obj_extension    => '.obj',

        ranlib           => "true",
        shared_defflag   => '/def:',
        shared_ldflag    => picker(default => "/LD /link",
                                   debug   => "/LDd /link"),
        shared_extension => '.dll',
        lib_extension    => sub { $disabled{shared} ? '.lib' : '_static.lib' },
        shared_import_extension => '.lib',

        bin_lflags       => '/link',
        exe_extension    => '.exe',
    },

    "win64-x86_64-cross-clang-cl" => {
        inherit_from     => [ "win64-cross-clang-cl" ],

        asm_arch         => "x86_64",
        perlasm_scheme   => "win64",

        cflags           => add("--target=x86_64-pc-windows-msvc"),
        ldflags          => add("--target=x86_64-pc-windows-msvc"),
    },

    "win64-aarch64-cross-clang-cl" => {
        inherit_from     => [ "win64-cross-clang-cl" ],

        asm_arch         => "aarch64",
        perlasm_scheme   => "win64",

        cflags           => add("--target=arm64-pc-windows-msvc"),
        ldflags          => add("--target=arm64-pc-windows-msvc"),
    },
);
