## -*- mode: perl; -*-
(
    "linux-e2k" => {
        inherit_from    => [ "linux-generic64" ],
        cflags          => add("-m64"),
        cxxflags        => add("-m64"),
        lib_cppflags    => add("-DL_ENDIAN"),
        multilib        => "64",
        bn_ops          => "SIXTY_FOUR_BIT_LONG",
        asm_arch        => "e2k",
    },
    "linux-e2kv6" => {
        inherit_from    => [ "linux-e2k" ],
        asm_arch        => "e2kv6",
    },
    "linux-e2kv7" => {
        inherit_from    => [ "linux-e2k" ],
        asm_arch        => "e2kv7",
    },
);
