=pod

=head1 NAME

passwd - compute password hashes

=head1 SYNOPSIS

B<openssl passwd>
[B<-crypt>]
[B<-salt string>]
[B<-quiet>]
[B<-table>]
{B<password>}

=head1 DESCRIPTION

The B<passwd> command computes the hashes of a list of passwords
passed on the command line, or the hash of a password typed at run-time.
Currently only the Unix standard algorithm B<crypt>
is implemented.

=head1 OPTIONS

=over 4

=item B<-crypt>

Use the B<crypt> algorithm (default).

=item B<-salt string>

Use the specified salt.

=item B<-quiet>

Don't output warnings when passwords are truncated.

=item B<-table>

In the output list, prepend the cleartext password and a TAB character
to each password hash.

=back

=head1 EXAMPLE

B<openssl passwd -salt xx password> prints B<xxj31ZMTZzkVA>.

=cut
