=pod

=head1 NAME

version - print OpenSSL version information

=head1 SYNOPSIS

B<openssl version>
[B<-a>]
[B<-v>]
[B<-b>]
[B<-o>]
[B<-f>]
[B<-p>]
[B<-d>]

=head1 DESCRIPTION

This command is used to print out version information about OpenSSL.

=head1 OPTIONS

=over 4

=item B<-a>

All information.
This is the same as setting all the other flags.

=item B<-v>

The current OpenSSL version.

=item B<-b>

The date the current version of OpenSSL was built.

=item B<-o>

Option information: various options set when the library was built.

=item B<-f>

Compilation flags.

=item B<-p>

Platform setting.

=item B<-d>

B<OPENSSLDIR> setting.

=back

=head1 NOTES

The output of B<openssl version -a> would typically be used when sending in a bug report.

=cut
