/*
 * Copyright 2023-2024 The OpenSSL Project Authors. All Rights Reserved.
 *
 * Licensed under the Apache License 2.0 (the "License").  You may not use
 * this file except in compliance with the License.  You can obtain a copy
 * in the file LICENSE in the source distribution or at
 * https://www.openssl.org/source/license.html
 */

#ifdef FIPS_MODULE
#include <openssl/types.h>

enum fips_config_id {
    FIPS_CONFIG_SECURITY_CHECKS = 1,
    FIPS_CONFIG_TLS1_PRF_EMS_CHECK,
    FIPS_CONFIG_NO_SHORT_MAC,
    FIPS_CONFIG_HMAC_KEY_CHECK,
    FIPS_CONFIG_KMAC_KEY_CHECK,
    FIPS_CONFIG_DRBG_TRUNC_DIGEST,
    FIPS_CONFIG_SIGNATURE_DIGEST_CHECK,
    FIPS_CONFIG_HKDF_DIGEST_CHECK,
    FIPS_CONFIG_TLS13_KDF_DIGEST_CHECK,
    FIPS_CONFIG_TLS1_PRF_DIGEST_CHECK,
    FIPS_CONFIG_SSHKDF_DIGEST_CHECK,
    FIPS_CONFIG_SSKDF_DIGEST_CHECK,
    FIPS_CONFIG_X963KDF_DIGEST_CHECK,
    FIPS_CONFIG_DSA_SIGN_DISABLED,
    FIPS_CONFIG_TDES_ENCRYPT_DISABLED,
    FIPS_CONFIG_RSA_PKCS15_PAD_DISABLED,
    FIPS_CONFIG_RSA_PSS_SALTLEN_CHECK,
    FIPS_CONFIG_RSA_SIGN_X931_PAD_DISABLED,
    FIPS_CONFIG_HKDF_KEY_CHECK,
    FIPS_CONFIG_KBKDF_KEY_CHECK,
    FIPS_CONFIG_TLS13_KDF_KEY_CHECK,
    FIPS_CONFIG_TLS1_PRF_KEY_CHECK,
    FIPS_CONFIG_SSHKDF_KEY_CHECK,
    FIPS_CONFIG_SSKDF_KEY_CHECK,
    FIPS_CONFIG_X963KDF_KEY_CHECK,
    FIPS_CONFIG_X942KDF_KEY_CHECK,
    FIPS_CONFIG_PBKDF2_LOWER_BOUND_CHECK,
    FIPS_CONFIG_ECDH_COFACTOR_CHECK,
};

int ossl_fips_config(OSSL_LIB_CTX *libctx, enum fips_config_id id);

#endif
