=pod

=head1 NAME

ossl_file_stat
- file-related auxiliary functions

=head1 SYNOPSIS

 #include <internal/e_os.h>

 const char *ossl_file_stat(const char *uri, struct stat *st);

=head1 DESCRIPTION

ossl_file_stat() is an auxiliary function
for handling URIs that may be interpreted as a reference to a local file.
It attempts to derive from the given I<uri> a file pathname that points to an
existing file. To this end it takes the full I<uri> as a filename (which may be
an absolute or relative name, such as C<file.pem>) or takes a postfix of I<uri>,
such as C<path-to-file> if the uri is of the form C<file:path-to-file>
or C</path-to-file> if the uri is of the form C<file://localhost/path-to-file>.
On success it populates the file stat buffer pointed at by I<st>
(unless I<st> is NULL) and returns the derived pathname, otherwise NULL.

=head1 RETURN VALUES

ossl_file_stat() returns a file pathname or NULL on error.

=head1 HISTORY

ossl_file_stat() was added in OpenSSL 3.6.

=head1 COPYRIGHT

Copyright 2016-2025 The OpenSSL Project Authors. All Rights Reserved.

Licensed under the Apache License 2.0 (the "License").  You may not use
this file except in compliance with the License.  You can obtain a copy
in the file LICENSE in the source distribution or at
L<https://www.openssl.org/source/license.html>.

=cut
