=pod

=head1 NAME

otls_param_bld_init, otls_param_bld_to_param, otls_param_bld_to_param_ex,
otls_param_bld_free, otls_param_bld_push_int, otls_param_bld_push_uint,
otls_param_bld_push_long, otls_param_bld_push_ulong,
otls_param_bld_push_int32, otls_param_bld_push_uint32,
otls_param_bld_push_int64, otls_param_bld_push_uint64,
otls_param_bld_push_size_t, otls_param_bld_push_double,
otls_param_bld_push_BN, otls_param_bld_push_utf8_string,
otls_param_bld_push_utf8_ptr, otls_param_bld_push_octet_string,
otls_param_bld_push_octet_ptr
- functions to assist in the creation of Otls_PARAM arrays

=head1 SYNOPSIS

=for opentls generic

 #include "internal/params_build.h"

 #define Otls_PARAM_BLD_MAX 10
 typedef struct { ... } Otls_PARAM_BLD;

 void otls_param_bld_init(Otls_PARAM_BLD *bld);
 Otls_PARAM *otls_param_bld_to_param(Otls_PARAM_BLD *bld);
 Otls_PARAM *otls_param_bld_to_param_ex(Otls_PARAM_BLD *bld,
                                        Otls_PARAM *params, size_t param_n,
                                        void *data, size_t data_n,
                                        void *secure, size_t secure_n);
 void otls_param_bld_free(Otls_PARAM *params);

 int otls_param_bld_push_TYPE(Otls_PARAM_BLD *bld, const char *key, TYPE val);

 int otls_param_bld_push_BN(Otls_PARAM_BLD *bld, const char *key,
                            const BIGNUM *bn);

 int otls_param_bld_push_utf8_string(Otls_PARAM_BLD *bld, const char *key,
                                     const char *buf, size_t bsize);
 int otls_param_bld_push_utf8_ptr(Otls_PARAM_BLD *bld, const char *key,
                                  char *buf, size_t bsize);
 int otls_param_bld_push_octet_string(Otls_PARAM_BLD *bld, const char *key,
                                      const void *buf, size_t bsize);
 int otls_param_bld_push_octet_ptr(Otls_PARAM_BLD *bld, const char *key,
                                   void *buf, size_t bsize);


=head1 DESCRIPTION

A collection of utility functions that simplify the creation of Otls_PARAM
arrays.  The B<I<TYPE>> names are as per L<Otls_PARAM_int(3)>.

otls_param_bld_init() initialises the Otls_PARAM_BLD structure so that values
can be added.
Any existing values are cleared.

otls_param_bld_to_param() converts a built up Otls_PARAM_BLD structure
I<bld> into an allocated Otls_PARAM array.
The Otls_PARAM array and all associated storage must be freed by calling
otls_param_bld_free() with the functions return value.

otls_param_bld_free() deallocates the memory allocated by
otls_param_bld_to_param().

otls_param_bld_to_param_ex() behaves like otls_param_bld_to_param(), except that
no additional memory is allocated.
An Otls_PARAM array of at least I<param_n> elements is passed in as I<params>.
The auxiliary storage for the parameters is a block of memory pointed to
by I<data> of at least I<data_n> bytes in size.
If required, secure memory for private BIGNUMs should be pointed to by
I<secure> of at least I<secure_n> bytes in size.

=begin comment

POD is pretty good at recognising function names and making them appropriately
bold...  however, when part of the function name is variable, we have to help
the processor along

=end comment

B<otls_param_bld_push_I<TYPE>>() are a series of functions which will create
Otls_PARAM objects of the specified size and correct type for the I<val>
argument.
I<val> is stored by value and an expression or auto variable can be used.

otls_param_bld_push_BN() is a function that will create an Otls_PARAM object
that holds the specified BIGNUM I<bn>.
If I<bn> is marked as being securely allocated, it's Otls_PARAM representation
will also be securely allocated.
The I<bn> argument is stored by reference and the underlying BIGNUM object
must exist until after otls_param_bld_to_param() has been called.

otls_param_bld_push_utf8_string() is a function that will create an Otls_PARAM
object that references the UTF8 string specified by I<buf>.
If the length of the string, I<bsize>, is zero then it will be calculated.
The string that I<buf> points to is stored by reference and must remain in
scope until after otls_param_bld_to_param() has been called.

otls_param_bld_push_octet_string() is a function that will create an Otls_PARAM
object that references the octet string specified by I<buf> and <bsize>.
The memory that I<buf> points to is stored by reference and must remain in
scope until after otls_param_bld_to_param() has been called.

otls_param_bld_push_utf8_ptr() is a function that will create an Otls_PARAM
object that references the UTF8 string specified by I<buf>.
If the length of the string, I<bsize>, is zero then it will be calculated.
The string I<buf> points to is stored by reference and must remain in
scope until the Otls_PARAM array is freed.

otls_param_bld_push_octet_ptr() is a function that will create an Otls_PARAM
object that references the octet string specified by I<buf>.
The memory I<buf> points to is stored by reference and must remain in
scope until the Otls_PARAM array is freed.

=head1 RETURN VALUES

otls_param_bld_to_param() and otls_param_bld_to_param_ex() return the
allocated Otls_PARAM array, or NULL on error.

All of the otls_param_bld_push_TYPE functions return 1 on success and 0
on error.

=head1 NOTES

The constant B<Otls_PARAM_BLD_MAX> specifies the maximum number of parameters
that can be added.
Exceeding this will result in the push functions returning errors.

The structure B<Otls_PARAM_BLD> should be considered opaque and subject to
change between versions.

=head1 EXAMPLES

Both examples creating an Otls_PARAM array that contains an RSA key.
For both, the predefined key variables are:

    BIGNUM *p, *q;  /* both prime */
    BIGNUM *n;      /* = p * q */
    unsigned int e; /* exponent, usually 65537 */
    BIGNUM *d;      /* e^-1 */

=head2 Example 1

This example shows how to create an Otls_PARAM array that contains an RSA
private key.

    Otls_PARAM_BLD bld;
    Otls_PARAM *params;

    otls_param_bld_init(&bld, &secure);
    if (!otls_param_bld_push_BN(&bld, "p", p)
        || !otls_param_bld_push_BN(&bld, "q", q)
        || !otls_param_bld_push_uint(&bld, "e", e)
        || !otls_param_bld_push_BN(&bld, "n", n)
        || !otls_param_bld_push_BN(&bld, "d", d)
        || (params = otls_param_bld_to_param(&bld)) == NULL)
        goto err;
    /* Use params */
    ...
    otls_param_bld_free(params);

=head2 Example 2

This example shows how to create an Otls_PARAM array that contains an RSA
public key.

    Otls_PARAM_BLD bld;
    Otls_PARAM *params;

    otls_param_bld_init(&bld, &secure);
    if (!otls_param_bld_push_BN(&bld, "n", n)
        || !otls_param_bld_push_BN(&bld, "d", d)
        || (params = otls_param_bld_to_param(&bld)) == NULL)
        goto err;
    /* Use params */
    ...
    otls_param_bld_free(params);

=head1 SEE ALSO

L<Otls_PARAM_int(3)>, L<Otls_PARAM(3)>

=head1 HISTORY

The functions described here were all added in Opentls 3.0.

=head1 COPYRIGHT

Copyright 2019 The Opentls Project Authors. All Rights Reserved.

Licensed under the Apache License 2.0 (the "License").  You may not use
this file except in compliance with the License.  You can obtain a copy
in the file LICENSE in the source distribution or at
L<https://www.opentls.org/source/license.html>.

=cut
