=pod

=head1 NAME

SSL_SESSION_free - free an allocated SSL_SESSION structure

=head1 SYNOPSIS

 #include <openssl/ssl.h>

 void SSL_SESSION_free(SSL_SESSION *session);

=head1 DESCRIPTION

SSL_SESSION_free() decrements the reference count of B<session> and removes
the B<SSL_SESSION> structure pointed to by B<session> and frees up the allocated
memory, if the the reference count has reached 0.

=head1 RETURN VALUES

SSL_SESSION_free() does not provide diagnostic information.

L<ssl(3)|ssl(3)>, L<SSL_get_session(3)|SSL_get_session(3)>

=cut
