=pod

=head1 NAME

SSL_pending - obtain number of readable bytes buffered in an SSL object

=head1 SYNOPSIS

 #include <openssl/ssl.h>

 int SSL_pending(SSL *ssl);

=head1 DESCRIPTION

SSL_pending() returns the number of bytes which are available inside
B<ssl> for immediate read.

=head1 NOTES

Data are received in blocks from the peer. Therefore data can be buffered
inside B<ssl> and are ready for immediate retrieval with
L<SSL_read(3)|SSL_read(3)>.

=head1 RETURN VALUES

The number of bytes pending is returned.

L<SSL_read(3)|SSL_read(3)>, L<ssl(3)|ssl(3)>

=cut
