www.microsoft.com:443
sectest.microsoft.com:443
https://sectest.microsoft.com/ClientAuth/test.asp
ssl3.netscape.com:443
ssl3.netscape.com:444
www.openmarket.com:443 - no session ID caching. - no swap

Servers
bad  www.openmarket.com	Open-Market-Secure-WebServer/V2.1
bad  www.microsoft.com	Server: Microsoft-IIS/3.0
good transact.netscape.com	Netscape-Enterprise/2.01

clients
good netscape
hmm  MSIE

