=pod

=head1 NAME

BIO_ctrl_pending - Find out how much bytes are buffered in a BIO

=head1 SYNOPSIS

 #include <openssl/bio.h>

 size_t BIO_ctrl_pending(BIO *bio);

=head1 DESCRIPTION

BIO_ctrl_pending() returns the number of bytes buffered in a BIO.

=head1 BUGS

When B<bio> is NULL, the OpenSSL library calls assert().

=head1 RETURN VALUES

The following return values can occur:

=over 4

=item E<gt>=0

The number of bytes pending the BIO.

=back

=head1 SEE ALSO

L<bio(3)|bio(3)>, L<BIO_s_mem(3)|BIO_s_mem(3)>,
L<BIO_new_bio_pair(3)|BIO_new_bio_pair(3)>
