=pod

=head1 NAME

BN_num_bits, BN_num_bytes, BN_num_bits_word - get BIGNUM size

=head1 SYNOPSIS

 #include <openssl/bn.h>

 int BN_num_bytes(const BIGNUM *a);

 int BN_num_bits(const BIGNUM *a);

 int BN_num_bits_word(BN_ULONG w);

=head1 DESCRIPTION

These functions return the size of a B<BIGNUM> in bytes or bits,
and the size of an unsigned integer in bits.

BN_num_bytes() is a macro.

=head1 RETURN VALUES

The size.

=head1 SEE ALSO

L<bn(3)|bn(3)>

=head1 HISTORY

BN_num_bytes(), BN_num_bits() and BN_num_bits_word() are available in
all versions of SSLeay and OpenSSL.

=cut
