=pod

=head1 NAME

d2i_DHparams, i2d_DHparams - ...

=head1 SYNOPSIS

 #include <openssl/dh.h>

 DH *d2i_DHparams(DH **a, unsigned char **pp, long length);
 int i2d_DHparams(DH *a, unsigned char **pp);

=head1 DESCRIPTION

...

=head1 RETURN VALUES

...

=head1 SEE ALSO

...

=head1 HISTORY

...

=cut
