=pod

=head1 NAME

DH_get_ex_new_index, DH_set_ex_data, DH_get_ex_data - ...

=head1 SYNOPSIS

 #include <openssl/dh.h>

 int DH_get_ex_new_index(long argl, char *argp, int (*new_func)(),
	     int (*dup_func)(), void (*free_func)());

 int DH_set_ex_data(DH *d, int idx, char *arg);

 char *DH_get_ex_data(DH *d, int idx);

=head1 DESCRIPTION

...

=head1 RETURN VALUES

...

=head1 SEE ALSO

...

=head1 HISTORY

...

=cut
