=pod

=head1 NAME

ERR_remove_thread_state, ERR_remove_state - free a thread's error queue

=head1 SYNOPSIS

 #include <openssl/err.h>

 void ERR_remove_thread_state(void);

Deprecated:

 #if OPENSSL_API_COMPAT < 0x10000000L
 void ERR_remove_state(unsigned long pid);
 #endif

=head1 DESCRIPTION

ERR_remove_thread_state() frees the error queue associated with the current
thread.

Since error queue data structures are allocated automatically for new
threads, they must be freed when threads are terminated in order to
avoid memory leaks.

ERR_remove_state is deprecated and has been replaced by
ERR_remove_thread_state. Any argument to this function is ignored and
calling ERR_remove_state is equivalent to B<ERR_remove_thread_state()>.

=head1 RETURN VALUE

ERR_remove_thread_state and ERR_remove_state() return no value.

=head1 SEE ALSO

L<err(3)>

=head1 HISTORY

ERR_remove_state()
was deprecated in OpenSSL 1.0.0 when ERR_remove_thread_state() was introduced.

=cut
