/*
 * Generated by util/mkerr.pl DO NOT EDIT
 * Copyright 1995-2017 The OpenSSL Project Authors. All Rights Reserved.
 *
 * Licensed under the OpenSSL license (the "License").  You may not use
 * this file except in compliance with the License.  You can obtain a copy
 * in the file LICENSE in the source distribution or at
 * https://www.openssl.org/source/license.html
 */

#include <stdio.h>
#include <openssl/err.h>
#include "internal/uri.h"

/* BEGIN ERROR CODES */
#ifndef OPENSSL_NO_ERR

# define ERR_FUNC(func) ERR_PACK(ERR_LIB_URI,func,0)
# define ERR_REASON(reason) ERR_PACK(ERR_LIB_URI,0,reason)

static ERR_STRING_DATA URI_str_functs[] = {
    {ERR_FUNC(URI_F_EXTRACT_AUTHORITY), "extract_authority"},
    {ERR_FUNC(URI_F_EXTRACT_FRAGMENT), "extract_fragment"},
    {ERR_FUNC(URI_F_EXTRACT_HOSTINFO), "extract_hostinfo"},
    {ERR_FUNC(URI_F_EXTRACT_PATH_ABEMPTY), "extract_path_abempty"},
    {ERR_FUNC(URI_F_EXTRACT_PATH_ABSOLUTE), "extract_path_absolute"},
    {ERR_FUNC(URI_F_EXTRACT_PATH_EMPTY), "extract_path_empty"},
    {ERR_FUNC(URI_F_EXTRACT_PATH_NOSCHEME), "extract_path_noscheme"},
    {ERR_FUNC(URI_F_EXTRACT_PATH_ROOTLESS), "extract_path_rootless"},
    {ERR_FUNC(URI_F_EXTRACT_QUERY), "extract_query"},
    {ERR_FUNC(URI_F_EXTRACT_SCHEME), "extract_scheme"},
    {ERR_FUNC(URI_F_EXTRACT_USERINFO), "extract_userinfo"},
    {ERR_FUNC(URI_F_OPENSSL_DECODE_AUTHORITY), "OPENSSL_decode_authority"},
    {ERR_FUNC(URI_F_OPENSSL_DECODE_URI), "OPENSSL_decode_uri"},
    {ERR_FUNC(URI_F_OPENSSL_PERCENT_DECODE_INLINE),
     "OPENSSL_percent_decode_inline"},
    {0, NULL}
};

static ERR_STRING_DATA URI_str_reasons[] = {
    {ERR_REASON(URI_R_FAILED_TO_DECODE_URI), "failed to decode uri"},
    {ERR_REASON(URI_R_INVALID_CHARACTER_IN_URI), "invalid character in uri"},
    {ERR_REASON(URI_R_INVALID_PERCENT_CODE), "invalid percent code"},
    {ERR_REASON(URI_R_MALFORMED_HOST_IN_URI), "malformed host in uri"},
    {ERR_REASON(URI_R_MALFORMED_PATH_IN_URI), "malformed path in uri"},
    {ERR_REASON(URI_R_PERCENT_NUL_UNSUPPORTED), "percent nul unsupported"},
    {0, NULL}
};

#endif

int ERR_load_URI_strings(void)
{
#ifndef OPENSSL_NO_ERR

    if (ERR_func_error_string(URI_str_functs[0].error) == NULL) {
        ERR_load_strings(0, URI_str_functs);
        ERR_load_strings(0, URI_str_reasons);
    }
#endif
    return 1;
}
