# Copyright 2025 The OpenSSL Project Authors. All Rights Reserved.
#
# Licensed under the Apache License 2.0 (the "License").  You may not use
# this file except in compliance with the License.  You can obtain a copy
# in the file LICENSE in the source distribution or at
# https://www.openssl.org/source/license.html

# Run assembler code paths

name: Assembler Testing

on: [pull_request, push]

permissions:
  contents: read

env:
  OPENSSL_SDE_PATH: ./downloads/sde-external-9.48.0-2024-11-25/sed64

jobs:
  x64_sde:
    strategy:
      fail-fast: false
      matrix:
        zoo: [
          {
            distro: ubuntu-latest,
            sde: sde-external-9.48.0-2024-11-25,
            download: 843185/sde-external-9.48.0-2024-11-25-lin
          }
        ]
    runs-on: ${{ matrix.zoo.distro }}
    env:
      sde_name: ${{ matrix.zoo.sde }}-lin
    steps:
      - name: create download directory
        run: mkdir downloads
      - name: download Intel SDE
        run: wget --no-verbose https://downloadmirror.intel.com/${{ matrix.zoo.download }}.tar.xz
        working-directory: downloads
      - name: unpack Intel SDE
        run: tar xf downloads/${sde_name}.tar.xz

      - uses: actions/checkout@v4
      - name: checkout fuzz/corpora submodule
        run: git submodule update --init --depth 1 fuzz/corpora
      - name: localegen
        run: sudo locale-gen tr_TR.UTF-8
      - name: config
        run: CC=gcc ./config --banner=Configured --strict-warnings && perl configdata.pm --dump
      - name: make
        run: make -s -j4
      - name: get cpu info
        run: |
          cat /proc/cpuinfo
          ./util/opensslwrap.sh version -c

      # SDE requires this line on ubuntu
      - name: Set ptrace_scope to 0
        run: |
          sudo sysctl -w kernel.yama.ptrace_scope=0

      - name: run tests
        run: make test TESTS="test_sde"

      - name: Restore ptrace_scope to 1
        run: |
          sudo sysctl -w kernel.yama.ptrace_scope=1
